--------------------------------------------------------
--  文件已创建 - 星期四-十一月-22-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APPLICANTS
--------------------------------------------------------

  CREATE TABLE "APPLICANTS" 
   (	"APPLICANTS_KEY" VARCHAR2(40), 
	"USER_NAME" VARCHAR2(100), 
	"USER_SEX" NUMBER(2,0), 
	"USER_EMAIL" VARCHAR2(100), 
	"BATCH_KEY" VARCHAR2(100), 
	"BATCH_NAME" VARCHAR2(100), 
	"PLAN_KEY" VARCHAR2(100), 
	"PLAN_NAME" VARCHAR2(100), 
	"DEPARTMENT_KEY" VARCHAR2(100), 
	"DEPARTMENT_NAME" VARCHAR2(100), 
	"POSITION_KEY" VARCHAR2(100), 
	"POSITION_NAME" VARCHAR2(100), 
	"SOURCE_" NUMBER(2,0), 
	"STATUS_" NUMBER(2,0), 
	"CREATE_TIME" TIMESTAMP (6)
   ) ;
/
--------------------------------------------------------
--  DDL for Table APPLICANTS_APPROVE
--------------------------------------------------------

  CREATE TABLE "APPLICANTS_APPROVE" 
   (	"APPLICANTS_APPROVE_KEY" VARCHAR2(40), 
	"APPLICANTS_KEY" VARCHAR2(40), 
	"APPLICANT_STATUS" NUMBER(2,0), 
	"SCORE_" VARCHAR2(100), 
	"RESULT_" NUMBER(2,0), 
	"OPINION_" CLOB, 
	"CREATE_TIME" TIMESTAMP (6)
   ) ;
/
--------------------------------------------------------
--  DDL for Table ARCHIVES
--------------------------------------------------------

  CREATE TABLE "ARCHIVES" 
   (	"X__STAFF_ID" VARCHAR2(50), 
	"X__NAME" VARCHAR2(50), 
	"ARCHIVES_ID" VARCHAR2(50), 
	"ARCHIVES_NAME" VARCHAR2(50), 
	"ARCHIVES_STATUS" CHAR(1), 
	"RECEIVE_DEPT_KEY" VARCHAR2(100), 
	"RECEIVE_DEPT" VARCHAR2(100), 
	"RECEIVE_TIME" VARCHAR2(50), 
	"RECEIVE_ATTN" VARCHAR2(50), 
	"RECEIVE_REASON" VARCHAR2(50), 
	"RECEIVE_NOTICE_NUMBER" VARCHAR2(50), 
	"RECEIPT_PROCESS" VARCHAR2(50), 
	"TRANSFER_PERSON" VARCHAR2(50), 
	"SOURCE_" VARCHAR2(50), 
	"LOCATION" VARCHAR2(200), 
	"REMARK" VARCHAR2(200), 
	"CREATE_TIME" VARCHAR2(50)
   ) ;
 

   COMMENT ON COLUMN "ARCHIVES"."X__STAFF_ID" IS '职工号';
 
   COMMENT ON COLUMN "ARCHIVES"."X__NAME" IS '员工姓名';
 
   COMMENT ON COLUMN "ARCHIVES"."ARCHIVES_ID" IS '档案编号';
 
   COMMENT ON COLUMN "ARCHIVES"."ARCHIVES_NAME" IS '档案名称';
 
   COMMENT ON COLUMN "ARCHIVES"."ARCHIVES_STATUS" IS '档案状态';
 
   COMMENT ON COLUMN "ARCHIVES"."RECEIVE_DEPT_KEY" IS '接收部门的编号';
 
   COMMENT ON COLUMN "ARCHIVES"."RECEIVE_DEPT" IS '接收部门名称';
 
   COMMENT ON COLUMN "ARCHIVES"."RECEIVE_TIME" IS '接收时间';
 
   COMMENT ON COLUMN "ARCHIVES"."RECEIVE_ATTN" IS '接收经办人';
 
   COMMENT ON COLUMN "ARCHIVES"."RECEIVE_REASON" IS '接收原因';
 
   COMMENT ON COLUMN "ARCHIVES"."RECEIVE_NOTICE_NUMBER" IS '接收通知单编号';
 
   COMMENT ON COLUMN "ARCHIVES"."RECEIPT_PROCESS" IS '回执处理';
 
   COMMENT ON COLUMN "ARCHIVES"."TRANSFER_PERSON" IS '移交人';
 
   COMMENT ON COLUMN "ARCHIVES"."SOURCE_" IS '来源';
 
   COMMENT ON COLUMN "ARCHIVES"."LOCATION" IS '保管地点';
 
   COMMENT ON COLUMN "ARCHIVES"."REMARK" IS '备注';
 
   COMMENT ON COLUMN "ARCHIVES"."CREATE_TIME" IS '创建时间';
/
--------------------------------------------------------
--  DDL for Table ARCHIVES_OPERATING_RECORDS
--------------------------------------------------------

  CREATE TABLE "ARCHIVES_OPERATING_RECORDS" 
   (	"ARCHIVES_OPERATING_RECORDS_ID" VARCHAR2(50), 
	"X__STAFF_ID" VARCHAR2(50), 
	"ARCHIVES_STATUS" CHAR(1), 
	"OPERATING_TIME" VARCHAR2(50), 
	"OPERATOR" VARCHAR2(50), 
	"TRANSACTION" VARCHAR2(50), 
	"VIEW_DETAIL" CLOB, 
	"CREATE_TIME" VARCHAR2(50)
   ) ;
 

   COMMENT ON COLUMN "ARCHIVES_OPERATING_RECORDS"."ARCHIVES_OPERATING_RECORDS_ID" IS '主键';
 
   COMMENT ON COLUMN "ARCHIVES_OPERATING_RECORDS"."X__STAFF_ID" IS '职工号';
 
   COMMENT ON COLUMN "ARCHIVES_OPERATING_RECORDS"."ARCHIVES_STATUS" IS '档案状态';
 
   COMMENT ON COLUMN "ARCHIVES_OPERATING_RECORDS"."OPERATING_TIME" IS '操作时间';
 
   COMMENT ON COLUMN "ARCHIVES_OPERATING_RECORDS"."OPERATOR" IS '操作者';
 
   COMMENT ON COLUMN "ARCHIVES_OPERATING_RECORDS"."TRANSACTION" IS '事务';
 
   COMMENT ON COLUMN "ARCHIVES_OPERATING_RECORDS"."VIEW_DETAIL" IS '操作记录详情（Json结构）';
 
   COMMENT ON COLUMN "ARCHIVES_OPERATING_RECORDS"."CREATE_TIME" IS '创建时间';
/
--------------------------------------------------------
--  DDL for Table AUDIT_LOGGING
--------------------------------------------------------

  CREATE TABLE "AUDIT_LOGGING" 
   (	"LOGGING_ID" VARCHAR2(40), 
	"AUDIT_TIME" DATE, 
	"AUDIT_DEPARTMENT_ID" VARCHAR2(40), 
	"AUDIT_USER_ID" VARCHAR2(40), 
	"AUDIT_VIEW" VARCHAR2(500), 
	"CURRENT_STEP_KEY" VARCHAR2(40), 
	"PLAN_ID" VARCHAR2(40), 
	"STATUS" NUMBER(5,0), 
	"CURRENT_STEP_NAME" VARCHAR2(50)
   ) ;
 

   COMMENT ON COLUMN "AUDIT_LOGGING"."LOGGING_ID" IS '??';
 
   COMMENT ON COLUMN "AUDIT_LOGGING"."AUDIT_TIME" IS '?????????';
 
   COMMENT ON COLUMN "AUDIT_LOGGING"."AUDIT_DEPARTMENT_ID" IS '?????Id';
 
   COMMENT ON COLUMN "AUDIT_LOGGING"."AUDIT_USER_ID" IS '?????id';
 
   COMMENT ON COLUMN "AUDIT_LOGGING"."AUDIT_VIEW" IS '????';
 
   COMMENT ON COLUMN "AUDIT_LOGGING"."CURRENT_STEP_KEY" IS '?';
 
   COMMENT ON COLUMN "AUDIT_LOGGING"."PLAN_ID" IS '???????id';
 
   COMMENT ON COLUMN "AUDIT_LOGGING"."STATUS" IS '??  0???   1????';
/
--------------------------------------------------------
--  DDL for Table CAMPUS_NOTICE
--------------------------------------------------------

  CREATE TABLE "CAMPUS_NOTICE" 
   (	"ID" VARCHAR2(40), 
	"TITLE" VARCHAR2(50), 
	"USERNAME" VARCHAR2(30), 
	"BEGIN_TIME" VARCHAR2(30), 
	"ACCESSORY" VARCHAR2(200), 
	"OVER_TIME" VARCHAR2(30), 
	"TYPE" VARCHAR2(2), 
	"CONTENT" CLOB, 
	"REMARK" VARCHAR2(4000)
   ) ;
/
--------------------------------------------------------
--  DDL for Table CODE_CATALOG
--------------------------------------------------------

  CREATE TABLE "CODE_CATALOG" 
   (	"CATALOG_ID" VARCHAR2(64), 
	"NAME" VARCHAR2(64), 
	"COPY_" VARCHAR2(64), 
	"DEFAULT_" NUMBER(*,0), 
	"SELECTABLE" NUMBER(*,0), 
	"REMARK" VARCHAR2(255)
   ) ;
/
--------------------------------------------------------
--  DDL for Table CONTRACT
--------------------------------------------------------

  CREATE TABLE "CONTRACT" 
   (	"CONTRACT_KEY" VARCHAR2(40), 
	"CONTRACT_ID" VARCHAR2(40), 
	"PERSONNEL_ID" VARCHAR2(40), 
	"DEPARTMENT_NAME" VARCHAR2(30), 
	"DEPARTMENT_ID" VARCHAR2(40), 
	"NAME" VARCHAR2(20), 
	"IDENTITY_CARD" VARCHAR2(20), 
	"SEX" NUMBER(2,0), 
	"POSITION_SORT" VARCHAR2(20), 
	"DUTY" VARCHAR2(20), 
	"TECH_TITLE" VARCHAR2(20), 
	"TYPE" NUMBER(2,0), 
	"STATUS" NUMBER(2,0), 
	"SIGN_TIME" TIMESTAMP (6), 
	"START_TIME" TIMESTAMP (6), 
	"END_TIME" TIMESTAMP (6), 
	"CHANGE_CAUSE" VARCHAR2(200), 
	"UPDATE_TIME" TIMESTAMP (6), 
	"WORK_FORM" VARCHAR2(30), 
	"REMARK" VARCHAR2(200), 
	"CONTRACT_PATH" VARCHAR2(50)
   ) ;
/
--------------------------------------------------------
--  DDL for Table COOKIE
--------------------------------------------------------

  CREATE TABLE "COOKIE" 
   (	"COOKIE_NAME" VARCHAR2(255), 
	"COOKIE_VALUE" VARCHAR2(4000), 
	"COOKIE_STAFF_ID" VARCHAR2(50)
   ) ;
/
--------------------------------------------------------
--  DDL for Table DATA_DICTIONARY_CATEGORY
--------------------------------------------------------

  CREATE TABLE "DATA_DICTIONARY_CATEGORY" 
   (	"CATEGORYID" VARCHAR2(50), 
	"NAME" VARCHAR2(50), 
	"REMARK" VARCHAR2(255)
   ) ;
/
--------------------------------------------------------
--  DDL for Table DATA_DICTIONARY_DEFINATION
--------------------------------------------------------

  CREATE TABLE "DATA_DICTIONARY_DEFINATION" 
   (	"DICTIONARYID" VARCHAR2(50), 
	"NAME" VARCHAR2(50), 
	"TABLENAME" VARCHAR2(50), 
	"CATEGORYID" VARCHAR2(50), 
	"COLUMNS" CLOB, 
	"REMARK" VARCHAR2(255), 
	"ATLESTRECORD" VARCHAR2(10), 
	"ATMOSTRECORD" VARCHAR2(10), 
	"SYNCHOVERALL" VARCHAR2(10)
   ) ;
/
--------------------------------------------------------
--  DDL for Table DEPARTMENTS
--------------------------------------------------------

  CREATE TABLE "DEPARTMENTS" 
   (	"DEPARTMENT_KEY" VARCHAR2(100), 
	"DEPARTMENT_NAME" VARCHAR2(255), 
	"PARENT_KEY" VARCHAR2(100), 
	"SORT_NUM" NUMBER(*,0), 
	"PHONE" VARCHAR2(255), 
	"FAX" VARCHAR2(255), 
	"CREATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(3000), 
	"DEPARTMENT_NUM" VARCHAR2(255 CHAR), 
	"SHORT_NAME" VARCHAR2(255 CHAR), 
	"ENGLISH_NAME" VARCHAR2(255 CHAR), 
	"LEADER_KEYS" VARCHAR2(255 CHAR), 
	"LEADER_NAMES" VARCHAR2(255 CHAR), 
	"ADDRESS" VARCHAR2(512 CHAR), 
	"DIVISION_KEY" VARCHAR2(255 CHAR), 
	"DIVISION_NAME" VARCHAR2(255 CHAR), 
	"LEVEL_KEY" VARCHAR2(255 CHAR), 
	"LEVEL_NAME" VARCHAR2(255 CHAR), 
	"FUNCTION_KEY" VARCHAR2(255 CHAR), 
	"FUNCTION_NAME" VARCHAR2(255 CHAR), 
	"PARENT_NAME" VARCHAR2(255 CHAR), 
	"FOUND_NUM" VARCHAR2(255 CHAR), 
	"CLOSE_NUM" VARCHAR2(255 CHAR), 
	"FOUND_DATE" TIMESTAMP (6), 
	"CLOSE_DATE" TIMESTAMP (6), 
	"PRE_PERSON_COUNT" NUMBER(*,0), 
	"FACT_PERSON_COUNT" NUMBER(*,0)
   ) ;
/
--------------------------------------------------------
--  DDL for Table DICTIONARY_DEFINATION_COPY
--------------------------------------------------------

  CREATE TABLE "DICTIONARY_DEFINATION_COPY" 
   (	"DICTIONARYID" VARCHAR2(50), 
	"NAME" VARCHAR2(50), 
	"TABLENAME" VARCHAR2(50), 
	"CATEGORYID" VARCHAR2(50), 
	"COLUMNS" CLOB, 
	"REMARK" VARCHAR2(255), 
	"ATLESTRECORD" VARCHAR2(10), 
	"ATMOSTRECORD" VARCHAR2(10), 
	"SYNCHOVERALL" VARCHAR2(10), 
	"TEST" CLOB
   ) ;
/
--------------------------------------------------------
--  DDL for Table DOCUMENT_
--------------------------------------------------------

  CREATE TABLE "DOCUMENT_" 
   (	"DOCUMENT_KEY" VARCHAR2(100), 
	"DOCUMENT_NAME" VARCHAR2(255), 
	"DOCUMENT_REMARK" VARCHAR2(3000), 
	"DOCUMENT_TYPE_KEY" VARCHAR2(255), 
	"DOCUMENT_TYPE_NAME" VARCHAR2(255), 
	"DOCUMENT_ICON" VARCHAR2(255), 
	"FILE_NAME" VARCHAR2(255), 
	"FILE_PATH" VARCHAR2(255), 
	"STATUS_" NUMBER(*,0), 
	"SORT_NUM" NUMBER(*,0), 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR_KEY" VARCHAR2(255), 
	"CREATOR_NAME" VARCHAR2(255)
   ) ;
/
--------------------------------------------------------
--  DDL for Table DOCUMENT_TYPE
--------------------------------------------------------

  CREATE TABLE "DOCUMENT_TYPE" 
   (	"DOCUMENT_TYPE_KEY" VARCHAR2(100), 
	"DOCUMENT_TYPE_NAME" VARCHAR2(255), 
	"DOCUMENT_TYPE_REMARK" VARCHAR2(3000), 
	"SORT_NUM" NUMBER(*,0), 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR_KEY" VARCHAR2(255), 
	"CREATOR_NAME" VARCHAR2(255)
   ) ;
/
--------------------------------------------------------
--  DDL for Table LINKS
--------------------------------------------------------

  CREATE TABLE "LINKS" 
   (	"INDEX_LINKS" VARCHAR2(50), 
	"NAME_LINKS" VARCHAR2(100), 
	"ADDR_LINKS" VARCHAR2(100), 
	"SEQUENCE_CODE" NUMBER(7,0), 
	"REMARK_LINKS" VARCHAR2(200)
   ) ;
/
--------------------------------------------------------
--  DDL for Table PERSONAL_DEFINITION
--------------------------------------------------------

  CREATE TABLE "PERSONAL_DEFINITION" 
   (	"PERSONAL_DEFINITION_KEY" VARCHAR2(40), 
	"PERSONAL_DEFINITION_COLUMNS" CLOB, 
	"PERSONAL_DEFINITION_TABLE_NAME" VARCHAR2(50)
   ) ;
/
--------------------------------------------------------
--  DDL for Table POSITION
--------------------------------------------------------

  CREATE TABLE "POSITION" 
   (	"POSITION_KEY" VARCHAR2(50), 
	"POSITION_NAME" VARCHAR2(30), 
	"POSITION_HNO" VARCHAR2(50), 
	"DEPARTMENT_KEY" VARCHAR2(50), 
	"DEPARTMENT_NAME" VARCHAR2(255 CHAR), 
	"SORT_NUM" VARCHAR2(255 CHAR), 
	"LEADER_KEYS" VARCHAR2(255 CHAR), 
	"LEADER_NAMES" VARCHAR2(255 CHAR), 
	"DIVISION_KEY" VARCHAR2(255 CHAR), 
	"DIVISION_NAME" VARCHAR2(255 CHAR), 
	"LEVEL_KEY" VARCHAR2(255 CHAR), 
	"LEVEL_NAME" VARCHAR2(255 CHAR), 
	"FOUND_NUM" VARCHAR2(255 CHAR), 
	"CLOSE_NUM" VARCHAR2(255 CHAR), 
	"FOUND_DATE" TIMESTAMP (6), 
	"CLOSE_DATE" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(3000 CHAR), 
	"PRE_PERSON_COUNT" NUMBER(*,0), 
	"FACT_PERSON_COUNT" NUMBER(*,0), 
	"CREATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_DATE" TIMESTAMP (6)
   ) ;
/
--------------------------------------------------------
--  DDL for Table RECRUIT_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "RECRUIT_ACCOUNT" 
   (	"ID" VARCHAR2(30), 
	"EMAIL" VARCHAR2(40), 
	"USERNAME" VARCHAR2(30), 
	"PASSWORD" VARCHAR2(30), 
	"LASTLOGINDATE" TIMESTAMP (6), 
	"CREATEDATE" TIMESTAMP (6)
   ) ;
/
--------------------------------------------------------
--  DDL for Table RECRUIT_AUDIT_STEP_DETAIL
--------------------------------------------------------

  CREATE TABLE "RECRUIT_AUDIT_STEP_DETAIL" 
   (	"RECRUITMENT_CATEGORY_NUMBER" NUMBER(7,0), 
	"AUDIT_DEPARTMENT_ID" VARCHAR2(50), 
	"AUDIT_DEPARTMENT_NAME" VARCHAR2(50), 
	"SORT_NUMBER" NUMBER(5,0), 
	"PRE_STEP_KEY" VARCHAR2(50), 
	"POST_STEP_KEY" VARCHAR2(50), 
	"CURRENT_STEP_KEY" VARCHAR2(50)
   ) ;
 

   COMMENT ON COLUMN "RECRUIT_AUDIT_STEP_DETAIL"."RECRUITMENT_CATEGORY_NUMBER" IS '?????Id';
 
   COMMENT ON COLUMN "RECRUIT_AUDIT_STEP_DETAIL"."AUDIT_DEPARTMENT_ID" IS '??????';
 
   COMMENT ON COLUMN "RECRUIT_AUDIT_STEP_DETAIL"."AUDIT_DEPARTMENT_NAME" IS '??????';
 
   COMMENT ON COLUMN "RECRUIT_AUDIT_STEP_DETAIL"."SORT_NUMBER" IS '???';
 
   COMMENT ON COLUMN "RECRUIT_AUDIT_STEP_DETAIL"."PRE_STEP_KEY" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_AUDIT_STEP_DETAIL"."POST_STEP_KEY" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_AUDIT_STEP_DETAIL"."CURRENT_STEP_KEY" IS '??,????????';
/
--------------------------------------------------------
--  DDL for Table RECRUIT_AUDIT_STEP_SETTING
--------------------------------------------------------

  CREATE TABLE "RECRUIT_AUDIT_STEP_SETTING" 
   (	"RECRUITMENT_CATEGORY_NUMBER" NUMBER(7,0), 
	"RECRUITMENT_CATEGORY_NAME" VARCHAR2(25), 
	"SET_AUDIT_STEP_PATH" VARCHAR2(100), 
	"RECRUITMENT_CATEGORY_REMARK" VARCHAR2(100), 
	"CURRENT_AUDIT_STATE" NUMBER(1,0), 
	"AUDIT_STEP_KEY" VARCHAR2(50), 
	"FLOW_KEY" VARCHAR2(50), 
	"VERSION_" NUMBER(9,0), 
	"IS_USING" NUMBER(1,0)
   ) ;
 

   COMMENT ON COLUMN "RECRUIT_AUDIT_STEP_SETTING"."RECRUITMENT_CATEGORY_NUMBER" IS '??';
 
   COMMENT ON COLUMN "RECRUIT_AUDIT_STEP_SETTING"."RECRUITMENT_CATEGORY_NAME" IS '??????';
 
   COMMENT ON COLUMN "RECRUIT_AUDIT_STEP_SETTING"."SET_AUDIT_STEP_PATH" IS '??????(????)';
 
   COMMENT ON COLUMN "RECRUIT_AUDIT_STEP_SETTING"."RECRUITMENT_CATEGORY_REMARK" IS '??';
 
   COMMENT ON COLUMN "RECRUIT_AUDIT_STEP_SETTING"."CURRENT_AUDIT_STATE" IS '??(1:??,0:??)';
/
--------------------------------------------------------
--  DDL for Table RECRUIT_BATCH_SETTING
--------------------------------------------------------

  CREATE TABLE "RECRUIT_BATCH_SETTING" 
   (	"BATCH_NO" VARCHAR2(40), 
	"BATCH_NAME" VARCHAR2(30), 
	"YEAR" VARCHAR2(20), 
	"BATCH_STATUS" NUMBER(10,0), 
	"CREATE_TIME" VARCHAR2(30), 
	"CLOSE_TIME" VARCHAR2(30), 
	"OPEN_TIME" VARCHAR2(30), 
	"BATCH_NUMBER" VARCHAR2(30)
   ) ;
 

   COMMENT ON COLUMN "RECRUIT_BATCH_SETTING"."BATCH_NO" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_BATCH_SETTING"."BATCH_NAME" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_BATCH_SETTING"."YEAR" IS '??';
 
   COMMENT ON COLUMN "RECRUIT_BATCH_SETTING"."BATCH_STATUS" IS '???0.?? 1.?? 2.???';
 
   COMMENT ON COLUMN "RECRUIT_BATCH_SETTING"."CREATE_TIME" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_BATCH_SETTING"."CLOSE_TIME" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_BATCH_SETTING"."OPEN_TIME" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_BATCH_SETTING"."BATCH_NUMBER" IS '?????????';
/
--------------------------------------------------------
--  DDL for Table RECRUIT_NOTICE
--------------------------------------------------------

  CREATE TABLE "RECRUIT_NOTICE" 
   (	"ID" VARCHAR2(40), 
	"TITLE" VARCHAR2(50), 
	"ACCESSORY" VARCHAR2(200), 
	"USERNAME" VARCHAR2(30), 
	"RECIPIENT_EMAIL" VARCHAR2(30), 
	"SENDTIME" VARCHAR2(30), 
	"USER_EMAIL" VARCHAR2(40), 
	"TYPE" VARCHAR2(15), 
	"REMARK" VARCHAR2(4000), 
	"CONTENT" CLOB
   ) ;
 

   COMMENT ON COLUMN "RECRUIT_NOTICE"."ID" IS '??';
 
   COMMENT ON COLUMN "RECRUIT_NOTICE"."TITLE" IS '??';
 
   COMMENT ON COLUMN "RECRUIT_NOTICE"."ACCESSORY" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_NOTICE"."USERNAME" IS '???';
 
   COMMENT ON COLUMN "RECRUIT_NOTICE"."RECIPIENT_EMAIL" IS '??????';
 
   COMMENT ON COLUMN "RECRUIT_NOTICE"."SENDTIME" IS '????';
/
--------------------------------------------------------
--  DDL for Table RECRUIT_PLAN
--------------------------------------------------------

  CREATE TABLE "RECRUIT_PLAN" 
   (	"PLAN_ID" VARCHAR2(38), 
	"YEAR" VARCHAR2(6), 
	"RECRUIT_DEPARTMENT_ID" VARCHAR2(50), 
	"RECRUIT_DEPARTMENT_NAME" VARCHAR2(50), 
	"OPEN_POSITIONS_ID" VARCHAR2(50), 
	"OPEN_POSITIONS_NAME" VARCHAR2(50), 
	"SUBJECT_ID" VARCHAR2(50), 
	"PROFESSIONAL_ID" VARCHAR2(50), 
	"PROFESSIONAL_FIELD_ID" VARCHAR2(50), 
	"TALENT_CATEGORY_ID" VARCHAR2(50), 
	"RECRUIT_METHOD_ID" VARCHAR2(50), 
	"RECRUIT_CATEGORY_ID" VARCHAR2(30), 
	"LOWEST_EDUCATION_ID" VARCHAR2(30), 
	"LOWEST_DEGREE_ID" VARCHAR2(30), 
	"LOWEST_TITLES_ID" VARCHAR2(30), 
	"RECRUIT_COUNT" VARCHAR2(5), 
	"FORMATION_CATEGORY_ID" VARCHAR2(30), 
	"TOP_TALENTS_ID" VARCHAR2(30), 
	"STATUS" NUMBER(4,0), 
	"CREATE_TIME" DATE, 
	"UPDATE_TIME" DATE, 
	"AUDIT_LINK_ID" VARCHAR2(40), 
	"DEPARTMENT_ID" VARCHAR2(40), 
	"DEPARTMENT_NAME" VARCHAR2(40), 
	"LOGGING_ID" VARCHAR2(40), 
	"PLAN_CREATE_METHOD" VARCHAR2(30), 
	"CURRENT_STEP_KEY" VARCHAR2(40), 
	"BATCH_NO" VARCHAR2(40), 
	"START_RELEASE_TIME" DATE, 
	"END_RELEASE_TIME" DATE, 
	"BATCH_NAME" VARCHAR2(30), 
	"CURRENT_DEPARTMENT_IDS" VARCHAR2(500), 
	"JOB_DUTY" CLOB, 
	"JOB_REQUEST" CLOB, 
	"REMARK" VARCHAR2(4000)
   ) ;
 

   COMMENT ON COLUMN "RECRUIT_PLAN"."PLAN_ID" IS '??';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."YEAR" IS '??';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."RECRUIT_DEPARTMENT_ID" IS '????Id';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."RECRUIT_DEPARTMENT_NAME" IS '??????';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."OPEN_POSITIONS_ID" IS '????id ';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."OPEN_POSITIONS_NAME" IS '??????';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."SUBJECT_ID" IS '??id';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."PROFESSIONAL_ID" IS '??id';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."PROFESSIONAL_FIELD_ID" IS '????id';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."TALENT_CATEGORY_ID" IS '????id';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."RECRUIT_METHOD_ID" IS '????id';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."RECRUIT_CATEGORY_ID" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."LOWEST_EDUCATION_ID" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."LOWEST_DEGREE_ID" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."LOWEST_TITLES_ID" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."RECRUIT_COUNT" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."FORMATION_CATEGORY_ID" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."TOP_TALENTS_ID" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."STATUS" IS '???1?????2?????3?????4????5?????5????';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."CREATE_TIME" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."UPDATE_TIME" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."AUDIT_LINK_ID" IS '??';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."DEPARTMENT_ID" IS '??????id';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."DEPARTMENT_NAME" IS '????????';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."LOGGING_ID" IS '????id';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."PLAN_CREATE_METHOD" IS '??????';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."CURRENT_STEP_KEY" IS '?????????Id';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."BATCH_NO" IS '??Id';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."START_RELEASE_TIME" IS '????????';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."END_RELEASE_TIME" IS '????????';
 
   COMMENT ON COLUMN "RECRUIT_PLAN"."BATCH_NAME" IS '????';
/
--------------------------------------------------------
--  DDL for Table RECRUIT_RESUME_DEFINITION
--------------------------------------------------------

  CREATE TABLE "RECRUIT_RESUME_DEFINITION" 
   (	"RESUME_DEFINITION_ID" VARCHAR2(50), 
	"RESUME_DEFINITION_TABLE_NAME" VARCHAR2(25), 
	"RESUME_DEFINITION_TABLE_TITLE" VARCHAR2(25), 
	"RESUME_DEFINITION_IS_OPEN" VARCHAR2(2), 
	"RESUME_DEFINITION_IS_REQUIRED" VARCHAR2(2), 
	"RESUME_DEFINITION_COLUMNS" CLOB, 
	"RESUME_TEMPLATE_KEY" VARCHAR2(10), 
	"DICTIONARY_DEFINATION_ID" VARCHAR2(50)
   ) ;
 

   COMMENT ON COLUMN "RECRUIT_RESUME_DEFINITION"."RESUME_DEFINITION_ID" IS '?????';
 
   COMMENT ON COLUMN "RECRUIT_RESUME_DEFINITION"."RESUME_DEFINITION_TABLE_NAME" IS '??';
 
   COMMENT ON COLUMN "RECRUIT_RESUME_DEFINITION"."RESUME_DEFINITION_TABLE_TITLE" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_RESUME_DEFINITION"."RESUME_DEFINITION_IS_OPEN" IS '????';
 
   COMMENT ON COLUMN "RECRUIT_RESUME_DEFINITION"."RESUME_DEFINITION_IS_REQUIRED" IS '?????????';
 
   COMMENT ON COLUMN "RECRUIT_RESUME_DEFINITION"."RESUME_DEFINITION_COLUMNS" IS '??';
 
   COMMENT ON COLUMN "RECRUIT_RESUME_DEFINITION"."RESUME_TEMPLATE_KEY" IS '?????';
 
   COMMENT ON COLUMN "RECRUIT_RESUME_DEFINITION"."DICTIONARY_DEFINATION_ID" IS '???????';
/
--------------------------------------------------------
--  DDL for Table RECRUIT_RESUME_TEMPLATE
--------------------------------------------------------

  CREATE TABLE "RECRUIT_RESUME_TEMPLATE" 
   (	"RESUME_TEMPLATE_ID" VARCHAR2(10), 
	"RESUME_TEMPLATE_NAME" VARCHAR2(25), 
	"RESUME_TEMPLATE_STATUS" VARCHAR2(2)
   ) ;
/
--------------------------------------------------------
--  DDL for Table STAFF_CAMPUS_DEPLOYMENT
--------------------------------------------------------

  CREATE TABLE "STAFF_CAMPUS_DEPLOYMENT" 
   (	"DEPLOYMENT_KEY" VARCHAR2(40), 
	"STAFF_ID" VARCHAR2(50), 
	"STAFF_NAME" VARCHAR2(50), 
	"APPROVAL_NUMBER" VARCHAR2(50), 
	"CURRENT_DEPT" VARCHAR2(50), 
	"CURRENT_POST" VARCHAR2(50), 
	"DEPLOY_DATE" DATE, 
	"DEPLOY_REASON" VARCHAR2(200), 
	"DEPLOY_POST" VARCHAR2(50), 
	"DEPLOY_DEPT" VARCHAR2(50), 
	"REMARK" VARCHAR2(500), 
	"DEPLOY_DEPT_KEY" VARCHAR2(50), 
	"DEPLOY_POST_KEY" VARCHAR2(40)
   ) ;
 

   COMMENT ON COLUMN "STAFF_CAMPUS_DEPLOYMENT"."DEPLOYMENT_KEY" IS '主键';
 
   COMMENT ON COLUMN "STAFF_CAMPUS_DEPLOYMENT"."STAFF_ID" IS '员工号';
 
   COMMENT ON COLUMN "STAFF_CAMPUS_DEPLOYMENT"."STAFF_NAME" IS '员工姓名';
 
   COMMENT ON COLUMN "STAFF_CAMPUS_DEPLOYMENT"."APPROVAL_NUMBER" IS '批准文号';
 
   COMMENT ON COLUMN "STAFF_CAMPUS_DEPLOYMENT"."CURRENT_DEPT" IS '当前部门';
 
   COMMENT ON COLUMN "STAFF_CAMPUS_DEPLOYMENT"."CURRENT_POST" IS '当前岗位';
 
   COMMENT ON COLUMN "STAFF_CAMPUS_DEPLOYMENT"."DEPLOY_DATE" IS '调岗日期';
 
   COMMENT ON COLUMN "STAFF_CAMPUS_DEPLOYMENT"."DEPLOY_REASON" IS '调配原因';
 
   COMMENT ON COLUMN "STAFF_CAMPUS_DEPLOYMENT"."DEPLOY_POST" IS '调配岗位';
 
   COMMENT ON COLUMN "STAFF_CAMPUS_DEPLOYMENT"."DEPLOY_DEPT" IS '调配部门';
 
   COMMENT ON COLUMN "STAFF_CAMPUS_DEPLOYMENT"."REMARK" IS '备注';
/
--------------------------------------------------------
--  DDL for Table STAFF_DEATH
--------------------------------------------------------

  CREATE TABLE "STAFF_DEATH" 
   (	"DEATH_KEY" VARCHAR2(40), 
	"STAFF_ID" VARCHAR2(50), 
	"NAME" VARCHAR2(50), 
	"DEATH_DATE" DATE, 
	"DEATH_REASON" VARCHAR2(200), 
	"DEATH_REMARK" VARCHAR2(500)
   ) ;
/
--------------------------------------------------------
--  DDL for Table STAFF_DEFINITION
--------------------------------------------------------

  CREATE TABLE "STAFF_DEFINITION" 
   (	"STAFF_DEFINITION_KEY" VARCHAR2(40), 
	"STAFF_DEFINITION_COLUMNS" CLOB, 
	"STAFF_DEFINITION_TABLE_NAME" VARCHAR2(50)
   ) ;
/
--------------------------------------------------------
--  DDL for Table STAFF_ENGAGE_POST
--------------------------------------------------------

  CREATE TABLE "STAFF_ENGAGE_POST" 
   (	"ENGAGE_POST_KEY" VARCHAR2(40), 
	"STAFF_ID" VARCHAR2(50), 
	"STAFF_NAME" VARCHAR2(60), 
	"ENGAGE_POST_TYPE" VARCHAR2(50), 
	"ENGAGE_POST_STATUS" NUMBER, 
	"ENGAGE_DEPART" VARCHAR2(100), 
	"ENGAGE_DEPART_KEY" VARCHAR2(40), 
	"ENGAGE_POST_LEVEL" VARCHAR2(50), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"REALLY_STOP_DATE" DATE
   ) ;
 

   COMMENT ON COLUMN "STAFF_ENGAGE_POST"."ENGAGE_POST_KEY" IS '主键';
 
   COMMENT ON COLUMN "STAFF_ENGAGE_POST"."STAFF_ID" IS '职工号';
 
   COMMENT ON COLUMN "STAFF_ENGAGE_POST"."STAFF_NAME" IS '职工姓名';
 
   COMMENT ON COLUMN "STAFF_ENGAGE_POST"."ENGAGE_POST_TYPE" IS '岗位类别';
 
   COMMENT ON COLUMN "STAFF_ENGAGE_POST"."ENGAGE_POST_STATUS" IS '聘岗状态0未聘1已聘2历史';
 
   COMMENT ON COLUMN "STAFF_ENGAGE_POST"."ENGAGE_DEPART" IS '聘任部门';
 
   COMMENT ON COLUMN "STAFF_ENGAGE_POST"."ENGAGE_DEPART_KEY" IS '聘任部门Key';
 
   COMMENT ON COLUMN "STAFF_ENGAGE_POST"."ENGAGE_POST_LEVEL" IS '岗位级别';
 
   COMMENT ON COLUMN "STAFF_ENGAGE_POST"."START_DATE" IS '开始日期';
 
   COMMENT ON COLUMN "STAFF_ENGAGE_POST"."END_DATE" IS '终止日期';
/
--------------------------------------------------------
--  DDL for Table STAFF_ENTRY
--------------------------------------------------------

  CREATE TABLE "STAFF_ENTRY" 
   (	"ENTRY_KEY" VARCHAR2(40), 
	"STAFF_ID" VARCHAR2(50), 
	"ENTRY_DATE" DATE, 
	"STAFF_SOURCE" VARCHAR2(50), 
	"APPROVALNUM" VARCHAR2(50), 
	"END_DATE" DATE, 
	"ENTRY_STATUS" VARCHAR2(50), 
	"STAFF_DELETE_STATUS" NUMBER, 
	"STAFF_NAME" VARCHAR2(60), 
	"REMARK" VARCHAR2(200), 
	"EXTEND_TIME" NUMBER, 
	"EXTEND_REASON" VARCHAR2(50), 
	"PROBATION_TIME" NUMBER
   ) ;
 

   COMMENT ON COLUMN "STAFF_ENTRY"."ENTRY_KEY" IS '入职表Key';
 
   COMMENT ON COLUMN "STAFF_ENTRY"."STAFF_ID" IS '职工号';
 
   COMMENT ON COLUMN "STAFF_ENTRY"."ENTRY_DATE" IS '入职日期';
 
   COMMENT ON COLUMN "STAFF_ENTRY"."STAFF_SOURCE" IS '教职工来源';
 
   COMMENT ON COLUMN "STAFF_ENTRY"."APPROVALNUM" IS '批准文号';
 
   COMMENT ON COLUMN "STAFF_ENTRY"."END_DATE" IS '试用到期日期';
 
   COMMENT ON COLUMN "STAFF_ENTRY"."ENTRY_STATUS" IS '18.在岗, 19试用';
 
   COMMENT ON COLUMN "STAFF_ENTRY"."STAFF_DELETE_STATUS" IS '0:删除,1:彻底删除';
 
   COMMENT ON COLUMN "STAFF_ENTRY"."STAFF_NAME" IS '职工姓名';
 
   COMMENT ON COLUMN "STAFF_ENTRY"."REMARK" IS '描述';
/
--------------------------------------------------------
--  DDL for Table STAFF_HISTORY
--------------------------------------------------------

  CREATE TABLE "STAFF_HISTORY" 
   (	"HISTORY_KEY" VARCHAR2(40), 
	"CHANGE_TYPE" VARCHAR2(40), 
	"CHANGE_REASON" VARCHAR2(50), 
	"CHANGE_DESC" VARCHAR2(100), 
	"CHANGE_RESULT" VARCHAR2(100), 
	"CHANGE_DATE" DATE, 
	"STAFF_ID" VARCHAR2(50), 
	"STAFF_NAME" VARCHAR2(60), 
	"CREATE_TIME" DATE, 
	"HISTORY_DETAIL_KEY" VARCHAR2(50), 
	"FORMER_STATUS" VARCHAR2(10)
   ) ;
 

   COMMENT ON COLUMN "STAFF_HISTORY"."HISTORY_KEY" IS '历史Key';
 
   COMMENT ON COLUMN "STAFF_HISTORY"."CHANGE_TYPE" IS '变动类型';
 
   COMMENT ON COLUMN "STAFF_HISTORY"."CHANGE_REASON" IS '变动原因';
 
   COMMENT ON COLUMN "STAFF_HISTORY"."CHANGE_DESC" IS '变动说明';
 
   COMMENT ON COLUMN "STAFF_HISTORY"."CHANGE_RESULT" IS '变动结果';
 
   COMMENT ON COLUMN "STAFF_HISTORY"."CHANGE_DATE" IS '变动日期';
 
   COMMENT ON COLUMN "STAFF_HISTORY"."STAFF_ID" IS '职工号';
 
   COMMENT ON COLUMN "STAFF_HISTORY"."STAFF_NAME" IS '职工姓名';
/
--------------------------------------------------------
--  DDL for Table STAFF_POSITIVE
--------------------------------------------------------

  CREATE TABLE "STAFF_POSITIVE" 
   (	"POSITIVE_KEY" VARCHAR2(40), 
	"STAFF_ID" VARCHAR2(40), 
	"STAFF_NAME" VARCHAR2(50), 
	"DEFER_POSITIVE" DATE, 
	"POSITIVE_REASON" VARCHAR2(200), 
	"APPROVAL_NUMBER" VARCHAR2(50), 
	"DEPARTMENT" VARCHAR2(50), 
	"POSITION" VARCHAR2(50), 
	"REMARK" VARCHAR2(500), 
	"REALLY_POSITIVE_DATE" DATE, 
	"POSITION_KEY" VARCHAR2(40), 
	"DEPARTMENT_KEY" VARCHAR2(40)
   ) ;
/
--------------------------------------------------------
--  DDL for Table STAFF_POST_CHANGE
--------------------------------------------------------

  CREATE TABLE "STAFF_POST_CHANGE" 
   (	"POST_CHANGE_KEY" VARCHAR2(50), 
	"STAFF_ID" VARCHAR2(50), 
	"STAFF_NAME" VARCHAR2(100), 
	"POST_NAME" VARCHAR2(100), 
	"POST_CATEGORY" VARCHAR2(50), 
	"POST_LEVEL" VARCHAR2(50), 
	"APPOINTMENT_DATE" DATE, 
	"APPOINTMENT_DEPT_KEY" VARCHAR2(50), 
	"APPOINTMENT_DEPT_NAME" VARCHAR2(100), 
	"APPROVE_DEPT_KEY" VARCHAR2(50), 
	"APPROVE_DEPT_NAME" VARCHAR2(100), 
	"APPROVAL_NUMBER" VARCHAR2(50), 
	"APPOINTMENT_MODE" VARCHAR2(300), 
	"WORK_CONTENT" VARCHAR2(200), 
	"APPOINTMENT_STATUS" VARCHAR2(10), 
	"MIDDLE_CADRES" CHAR(1), 
	"PART_TIME" CHAR(1), 
	"REMARK" VARCHAR2(300), 
	"DISMISSAL_DATE" DATE, 
	"DISMISSAL_REASON" VARCHAR2(300), 
	"CURRENT_STATUS" CHAR(1), 
	"CREATE_TIME" DATE, 
	"POST_CATEGORY_KEY" VARCHAR2(50), 
	"POST_LEVEL_KEY" VARCHAR2(50), 
	"APPOINTMENT_MODE_KEY" VARCHAR2(50), 
	"DISMISSAL_REASON_KEY" VARCHAR2(50), 
	"APPOINTMENT_END_DATE" DATE, 
	"APPOINTMENT_REASON" VARCHAR2(50), 
	"APPOINTMENT_REASON_KEY" VARCHAR2(50)
   ) ;
 

   COMMENT ON COLUMN "STAFF_POST_CHANGE"."POST_CHANGE_KEY" IS '主键';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."STAFF_ID" IS '人员编号';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."STAFF_NAME" IS '姓名';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."POST_NAME" IS '职务名称';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."POST_CATEGORY" IS '职务类别名称';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."POST_LEVEL" IS '职务级别名称';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."APPOINTMENT_DATE" IS '任职开始日期';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."APPOINTMENT_DEPT_KEY" IS '任职部门编号';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."APPOINTMENT_DEPT_NAME" IS '任职部门名称';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."APPROVE_DEPT_KEY" IS '任职批准单位编号';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."APPROVE_DEPT_NAME" IS '任职批准单位名称';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."APPROVAL_NUMBER" IS '批准文号';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."APPOINTMENT_MODE" IS '任职方式名称';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."WORK_CONTENT" IS '主管或从事的工作';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."APPOINTMENT_STATUS" IS '当前任职状况';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."MIDDLE_CADRES" IS '是否中层干部(取值1或空)';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."PART_TIME" IS '是否兼职(取值1或空)';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."REMARK" IS '备注';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."DISMISSAL_DATE" IS '免职日期';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."DISMISSAL_REASON" IS '免职原因';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."CURRENT_STATUS" IS '当前状态';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."CREATE_TIME" IS '创建日期';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."POST_CATEGORY_KEY" IS '职务类别编号';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."POST_LEVEL_KEY" IS '职务级别编号';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."APPOINTMENT_MODE_KEY" IS '任职方式编号';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."DISMISSAL_REASON_KEY" IS '免职原因编号';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."APPOINTMENT_END_DATE" IS '任职结束日期';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."APPOINTMENT_REASON" IS '任职原因';
 
   COMMENT ON COLUMN "STAFF_POST_CHANGE"."APPOINTMENT_REASON_KEY" IS '任职原因编号';
/
--------------------------------------------------------
--  DDL for Table STAFF_REHELLORING
--------------------------------------------------------

  CREATE TABLE "STAFF_REHELLORING" 
   (	"REHELLORING_KEY" VARCHAR2(40), 
	"STAFF_ID" VARCHAR2(50), 
	"STAFF_NAME" VARCHAR2(60), 
	"REHELLORING_DEPT" VARCHAR2(50), 
	"APPROVAL_NUM" VARCHAR2(50), 
	"CHANGE_REASON" VARCHAR2(100), 
	"POST_TYPE" VARCHAR2(30), 
	"POST_LEVEL" VARCHAR2(30), 
	"AGREEMENT" NUMBER(1,0), 
	"WORK_THIRTY_AGE" NUMBER(1,0), 
	"SPECIAL_PERSON" NUMBER(1,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"REMARK" VARCHAR2(200), 
	"REHELLORING_STATUS" VARCHAR2(50), 
	"STOP_DATE" DATE, 
	"STOP_REASON" VARCHAR2(100), 
	"STOP_DEPT" VARCHAR2(50), 
	"STOP_APPROVAL_NUM" VARCHAR2(50), 
	"STOP_REMARK" VARCHAR2(200), 
	"REHELLORING_DEPT_KEY" VARCHAR2(50), 
	"REHELLORING_POST" VARCHAR2(50), 
	"REHELLORING_POST_KEY" VARCHAR2(50), 
	"STOP_DEPT_KEY" VARCHAR2(50)
   ) ;
 

   COMMENT ON COLUMN "STAFF_REHELLORING"."REHELLORING_KEY" IS '主键';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."STAFF_ID" IS '职工号';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."STAFF_NAME" IS '职工姓名';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."REHELLORING_DEPT" IS '返聘部门';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."APPROVAL_NUM" IS '返聘批准文号';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."CHANGE_REASON" IS '变动原因';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."POST_TYPE" IS '返聘岗位类型';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."POST_LEVEL" IS '返聘岗位级别';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."AGREEMENT" IS '是否签订返聘协议';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."WORK_THIRTY_AGE" IS '是否30年工龄';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."SPECIAL_PERSON" IS '是否特殊人物';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."START_DATE" IS '返聘开始日期';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."END_DATE" IS '返聘结束日期';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."REMARK" IS '备注';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."REHELLORING_STATUS" IS '返聘人员状态(返聘/退休)';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."STOP_DATE" IS '终止返聘日期';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."STOP_REASON" IS '终止返聘原因';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."STOP_DEPT" IS '终止返聘后部门';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."STOP_APPROVAL_NUM" IS '终止返聘批准文号';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."STOP_REMARK" IS '终止返聘描述';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."REHELLORING_DEPT_KEY" IS '返聘部门Key';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."REHELLORING_POST" IS '返聘岗位';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."REHELLORING_POST_KEY" IS '返聘岗位编码';
 
   COMMENT ON COLUMN "STAFF_REHELLORING"."STOP_DEPT_KEY" IS '终止返聘后部门key';
/
--------------------------------------------------------
--  DDL for Table STAFF_RESIGNATION
--------------------------------------------------------

  CREATE TABLE "STAFF_RESIGNATION" 
   (	"ID" VARCHAR2(40), 
	"STAFF_ID" VARCHAR2(40), 
	"RESIGNATION_DATE" DATE, 
	"APPOINT_FILE_NUMBER" VARCHAR2(100), 
	"RESIGNATION_REASON" VARCHAR2(500), 
	"REMARK" CLOB
   ) ;
 

   COMMENT ON COLUMN "STAFF_RESIGNATION"."ID" IS '主键';
 
   COMMENT ON COLUMN "STAFF_RESIGNATION"."STAFF_ID" IS '员工编号';
 
   COMMENT ON COLUMN "STAFF_RESIGNATION"."RESIGNATION_DATE" IS '离职日期';
 
   COMMENT ON COLUMN "STAFF_RESIGNATION"."APPOINT_FILE_NUMBER" IS '批准文号';
 
   COMMENT ON COLUMN "STAFF_RESIGNATION"."RESIGNATION_REASON" IS '辞（离）职原因';
 
   COMMENT ON COLUMN "STAFF_RESIGNATION"."REMARK" IS '描述';
/
--------------------------------------------------------
--  DDL for Table STAFF_RETIREMENT
--------------------------------------------------------

  CREATE TABLE "STAFF_RETIREMENT" 
   (	"ID" VARCHAR2(40), 
	"STAFF_ID" VARCHAR2(40), 
	"RETIRE_REASON" VARCHAR2(40), 
	"RETIRE_DATE" DATE, 
	"RETIREE_PREMIUMS_PROPORTION" NUMBER(4,2), 
	"RETURN_OVERSEAS" NUMBER(4,2), 
	"PROPORTION_TOTAL" NUMBER(4,2), 
	"REMARK" CLOB, 
	"THREETY_STAFF_SERVICE" NUMBER(1,0), 
	"SPECIAL_STAFF" NUMBER(1,0), 
	"ONLY_CHILD" NUMBER(1,0), 
	"OVERSEAS_CHINESE" NUMBER(1,0)
   ) ;
 

   COMMENT ON COLUMN "STAFF_RETIREMENT"."ID" IS '主键';
 
   COMMENT ON COLUMN "STAFF_RETIREMENT"."STAFF_ID" IS '员工编号';
 
   COMMENT ON COLUMN "STAFF_RETIREMENT"."RETIRE_REASON" IS '退休原因';
 
   COMMENT ON COLUMN "STAFF_RETIREMENT"."RETIRE_DATE" IS '退休日期';
 
   COMMENT ON COLUMN "STAFF_RETIREMENT"."RETIREE_PREMIUMS_PROPORTION" IS '退休费计发比例';
 
   COMMENT ON COLUMN "STAFF_RETIREMENT"."RETURN_OVERSEAS" IS '归侨比例';
 
   COMMENT ON COLUMN "STAFF_RETIREMENT"."PROPORTION_TOTAL" IS '比例总计';
 
   COMMENT ON COLUMN "STAFF_RETIREMENT"."REMARK" IS '备注';
 
   COMMENT ON COLUMN "STAFF_RETIREMENT"."THREETY_STAFF_SERVICE" IS '是否30年工龄';
 
   COMMENT ON COLUMN "STAFF_RETIREMENT"."SPECIAL_STAFF" IS '是否特殊人员';
 
   COMMENT ON COLUMN "STAFF_RETIREMENT"."ONLY_CHILD" IS '是否独生子女';
 
   COMMENT ON COLUMN "STAFF_RETIREMENT"."OVERSEAS_CHINESE" IS '是否华侨';
/
--------------------------------------------------------
--  DDL for Table SYS_CONFIG
--------------------------------------------------------

  CREATE TABLE "SYS_CONFIG" 
   (	"KEY" VARCHAR2(50), 
	"VALUE" CLOB
   ) ;
/
--------------------------------------------------------
--  DDL for Table TASK
--------------------------------------------------------

  CREATE TABLE "TASK" 
   (	"TASK_KEY" VARCHAR2(40), 
	"TASK_NAME" VARCHAR2(50), 
	"TASK_STATUS" NUMBER(1,0), 
	"TASK_SCOPE" VARCHAR2(50), 
	"TASK_START_TIME" DATE, 
	"TASK_END_TIME" DATE, 
	"CREATOR" VARCHAR2(20), 
	"CREATE_TIME" TIMESTAMP (6)
   ) ;
 

   COMMENT ON COLUMN "TASK"."TASK_STATUS" IS '0:关闭,1:开启';
/
--------------------------------------------------------
--  DDL for Table TASK_DEFINITION
--------------------------------------------------------

  CREATE TABLE "TASK_DEFINITION" 
   (	"TASK_DEFINITION_KEY" VARCHAR2(40), 
	"TASK_DEFINITION_TABLE_NAME" VARCHAR2(50), 
	"TASK_DEFINITION_TABLE_TITLE" VARCHAR2(100), 
	"TASK_DEFINITION_IS_OPEN" NUMBER(1,0), 
	"TASK_KEY" VARCHAR2(40), 
	"TASK_DEFINITION_COLUMNS" CLOB, 
	"DICTIONARY_DEFINATION_ID" VARCHAR2(40), 
	"CREATOR" VARCHAR2(20), 
	"CREATE_TIME" TIMESTAMP (6)
   ) ;
 

   COMMENT ON COLUMN "TASK_DEFINITION"."TASK_DEFINITION_IS_OPEN" IS '0:不开放,1:开放';
/
--------------------------------------------------------
--  DDL for Table TASK_RECORD
--------------------------------------------------------

  CREATE TABLE "TASK_RECORD" 
   (	"TASK_RECORD_KEY" VARCHAR2(40), 
	"TASK_RECORD_DATA" CLOB, 
	"TASK_RECORD_APPLICANT" VARCHAR2(25), 
	"TASK_RECORD_APPLICANT_STAFF_ID" VARCHAR2(40), 
	"TASK_RECORD_APPLICATION_TIME" TIMESTAMP (6), 
	"TASK_RECORD_AUDITOR" VARCHAR2(25), 
	"TASK_RECORD_AUDIT_TIME" TIMESTAMP (6), 
	"TASK_RECORD_AUDIT_ADVISE" VARCHAR2(50), 
	"TASK_RECORD_AUDITOR_STAFF_ID" VARCHAR2(40), 
	"REMARK" VARCHAR2(50), 
	"TASK_KEY" VARCHAR2(40), 
	"CREATOR" VARCHAR2(20), 
	"CREATE_TIME" TIMESTAMP (6), 
	"TASK_RECORD_STATUS" NUMBER(1,0)
   ) ;
/
--------------------------------------------------------
--  DDL for Table VALIDATION_RULE
--------------------------------------------------------

  CREATE TABLE "VALIDATION_RULE" 
   (	"VALIDATION_RULE_ID" VARCHAR2(20), 
	"VALIDATION_RULE_NAME" VARCHAR2(20), 
	"VALIDATION_RULE_VALUE" VARCHAR2(4000), 
	"VALIDATION_RULE_FAIL_INFO" VARCHAR2(4000), 
	"VALIDATION_RULE_REMARK" VARCHAR2(4000)
   ) ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006598
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006598" ON "APPLICANTS" ("APPLICANTS_KEY") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006600
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006600" ON "APPLICANTS_APPROVE" ("APPLICANTS_APPROVE_KEY") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006602
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006602" ON "ARCHIVES" ("X__STAFF_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006605
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006605" ON "ARCHIVES_OPERATING_RECORDS" ("ARCHIVES_OPERATING_RECORDS_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006606
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006606" ON "AUDIT_LOGGING" ("LOGGING_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006608
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006608" ON "CAMPUS_NOTICE" ("ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006612
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006612" ON "CODE_CATALOG" ("CATALOG_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006614
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006614" ON "CONTRACT" ("CONTRACT_KEY") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_COOKIE_NAME_AND_STAFF_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_COOKIE_NAME_AND_STAFF_ID" ON "COOKIE" ("COOKIE_NAME", "COOKIE_STAFF_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index CATEGORY_CATEGORYID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CATEGORY_CATEGORYID_PK" ON "DATA_DICTIONARY_CATEGORY" ("CATEGORYID") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_DEFINATIONID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_DEFINATIONID" ON "DATA_DICTIONARY_DEFINATION" ("DICTIONARYID") 
  ;
/
--------------------------------------------------------
--  DDL for Index INDEX_DICTIONARY_DEFINATION
--------------------------------------------------------

  CREATE INDEX "INDEX_DICTIONARY_DEFINATION" ON "DATA_DICTIONARY_DEFINATION" ("NAME", "TABLENAME") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006620
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006620" ON "DEPARTMENTS" ("DEPARTMENT_KEY") 
  ;
/
--------------------------------------------------------
--  DDL for Index A_DICTIONARYID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "A_DICTIONARYID_PK" ON "DICTIONARY_DEFINATION_COPY" ("DICTIONARYID") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006757
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006757" ON "DOCUMENT_" ("DOCUMENT_KEY") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006759
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006759" ON "DOCUMENT_TYPE" ("DOCUMENT_TYPE_KEY") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006789
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006789" ON "LINKS" ("INDEX_LINKS") 
  ;
/
--------------------------------------------------------
--  DDL for Index POSITION_PK_POSITION_KEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "POSITION_PK_POSITION_KEY" ON "POSITION" ("POSITION_KEY") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ID" ON "RECRUIT_ACCOUNT" ("ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index CURRENT_STEP_KEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURRENT_STEP_KEY" ON "RECRUIT_AUDIT_STEP_DETAIL" ("CURRENT_STEP_KEY") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006810
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006810" ON "RECRUIT_AUDIT_STEP_SETTING" ("RECRUITMENT_CATEGORY_NUMBER") 
  ;
/
--------------------------------------------------------
--  DDL for Index BATCH_SETTING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BATCH_SETTING_PK" ON "RECRUIT_BATCH_SETTING" ("BATCH_NO") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006812
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006812" ON "RECRUIT_NOTICE" ("ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006813
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006813" ON "RECRUIT_PLAN" ("PLAN_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_RESUME_DEFINITION_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_RESUME_DEFINITION_ID" ON "RECRUIT_RESUME_DEFINITION" ("RESUME_DEFINITION_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index INDEX_RESUME_DEFINITION
--------------------------------------------------------

  CREATE INDEX "INDEX_RESUME_DEFINITION" ON "RECRUIT_RESUME_DEFINITION" ("RESUME_DEFINITION_TABLE_NAME", "RESUME_DEFINITION_TABLE_TITLE") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_TEMPLATE_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TEMPLATE_ID" ON "RECRUIT_RESUME_TEMPLATE" ("RESUME_TEMPLATE_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index ENGAGE_POST_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENGAGE_POST_KEY_PK" ON "STAFF_ENGAGE_POST" ("ENGAGE_POST_KEY") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006824
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006824" ON "STAFF_ENTRY" ("ENTRY_KEY") 
  ;
/
--------------------------------------------------------
--  DDL for Index HISTORY_HISTORY_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HISTORY_HISTORY_KEY_PK" ON "STAFF_HISTORY" ("HISTORY_KEY") 
  ;
/
--------------------------------------------------------
--  DDL for Index POST_CHANGE_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "POST_CHANGE_KEY_PK" ON "STAFF_POST_CHANGE" ("POST_CHANGE_KEY") 
  ;
/
--------------------------------------------------------
--  DDL for Index REHELLORING_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REHELLORING_KEY_PK" ON "STAFF_REHELLORING" ("REHELLORING_KEY") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006830
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006830" ON "STAFF_RESIGNATION" ("ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006831
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006831" ON "STAFF_RETIREMENT" ("ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C006832
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C006832" ON "SYS_CONFIG" ("KEY") 
  ;
/
--------------------------------------------------------
--  DDL for Index TASK_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TASK_KEY_PK" ON "TASK" ("TASK_KEY") 
  ;
/
--------------------------------------------------------
--  DDL for Index TASK_DEFINITION_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TASK_DEFINITION_KEY_PK" ON "TASK_DEFINITION" ("TASK_DEFINITION_KEY") 
  ;
/
--------------------------------------------------------
--  DDL for Index TASK_RECORD_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TASK_RECORD_KEY_PK" ON "TASK_RECORD" ("TASK_RECORD_KEY") 
  ;
/
--------------------------------------------------------
--  DDL for Index VALIDATION_RULE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VALIDATION_RULE_PK" ON "VALIDATION_RULE" ("VALIDATION_RULE_ID") 
  ;
/
--------------------------------------------------------
--  Constraints for Table APPLICANTS
--------------------------------------------------------

  ALTER TABLE "APPLICANTS" MODIFY ("APPLICANTS_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "APPLICANTS" ADD PRIMARY KEY ("APPLICANTS_KEY") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table APPLICANTS_APPROVE
--------------------------------------------------------

  ALTER TABLE "APPLICANTS_APPROVE" MODIFY ("APPLICANTS_APPROVE_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "APPLICANTS_APPROVE" ADD PRIMARY KEY ("APPLICANTS_APPROVE_KEY") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table ARCHIVES
--------------------------------------------------------

  ALTER TABLE "ARCHIVES" MODIFY ("X__STAFF_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ARCHIVES" ADD PRIMARY KEY ("X__STAFF_ID") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table ARCHIVES_OPERATING_RECORDS
--------------------------------------------------------

  ALTER TABLE "ARCHIVES_OPERATING_RECORDS" MODIFY ("ARCHIVES_OPERATING_RECORDS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ARCHIVES_OPERATING_RECORDS" MODIFY ("X__STAFF_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ARCHIVES_OPERATING_RECORDS" ADD PRIMARY KEY ("ARCHIVES_OPERATING_RECORDS_ID") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table AUDIT_LOGGING
--------------------------------------------------------

  ALTER TABLE "AUDIT_LOGGING" ADD PRIMARY KEY ("LOGGING_ID") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table CAMPUS_NOTICE
--------------------------------------------------------

  ALTER TABLE "CAMPUS_NOTICE" ADD PRIMARY KEY ("ID") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table CODE_CATALOG
--------------------------------------------------------

  ALTER TABLE "CODE_CATALOG" ADD PRIMARY KEY ("CATALOG_ID") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table CONTRACT
--------------------------------------------------------

  ALTER TABLE "CONTRACT" MODIFY ("CONTRACT_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "CONTRACT" ADD PRIMARY KEY ("CONTRACT_KEY") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table COOKIE
--------------------------------------------------------

  ALTER TABLE "COOKIE" ADD CONSTRAINT "PK_COOKIE_NAME_AND_STAFF_ID" PRIMARY KEY ("COOKIE_NAME", "COOKIE_STAFF_ID") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table DATA_DICTIONARY_CATEGORY
--------------------------------------------------------

  ALTER TABLE "DATA_DICTIONARY_CATEGORY" ADD CONSTRAINT "CATEGORY_CATEGORYID_PK" PRIMARY KEY ("CATEGORYID") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table DATA_DICTIONARY_DEFINATION
--------------------------------------------------------

  ALTER TABLE "DATA_DICTIONARY_DEFINATION" ADD CONSTRAINT "PK_DEFINATIONID" PRIMARY KEY ("DICTIONARYID") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table DEPARTMENTS
--------------------------------------------------------

  ALTER TABLE "DEPARTMENTS" ADD PRIMARY KEY ("DEPARTMENT_KEY") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table DICTIONARY_DEFINATION_COPY
--------------------------------------------------------

  ALTER TABLE "DICTIONARY_DEFINATION_COPY" ADD CONSTRAINT "A_DICTIONARYID_PK" PRIMARY KEY ("DICTIONARYID") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table DOCUMENT_
--------------------------------------------------------

  ALTER TABLE "DOCUMENT_" MODIFY ("DOCUMENT_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "DOCUMENT_" ADD PRIMARY KEY ("DOCUMENT_KEY") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table DOCUMENT_TYPE
--------------------------------------------------------

  ALTER TABLE "DOCUMENT_TYPE" MODIFY ("DOCUMENT_TYPE_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "DOCUMENT_TYPE" ADD PRIMARY KEY ("DOCUMENT_TYPE_KEY") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table LINKS
--------------------------------------------------------

  ALTER TABLE "LINKS" ADD PRIMARY KEY ("INDEX_LINKS") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table PERSONAL_DEFINITION
--------------------------------------------------------

  ALTER TABLE "PERSONAL_DEFINITION" MODIFY ("PERSONAL_DEFINITION_KEY" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table POSITION
--------------------------------------------------------

  ALTER TABLE "POSITION" ADD CONSTRAINT "POSITION_PK_POSITION_KEY" PRIMARY KEY ("POSITION_KEY") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table RECRUIT_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "RECRUIT_ACCOUNT" ADD CONSTRAINT "PK_ID" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "RECRUIT_ACCOUNT" MODIFY ("ID" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table RECRUIT_AUDIT_STEP_DETAIL
--------------------------------------------------------

  ALTER TABLE "RECRUIT_AUDIT_STEP_DETAIL" ADD CONSTRAINT "CURRENT_STEP_KEY" PRIMARY KEY ("CURRENT_STEP_KEY") ENABLE;
 
  ALTER TABLE "RECRUIT_AUDIT_STEP_DETAIL" MODIFY ("RECRUITMENT_CATEGORY_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "RECRUIT_AUDIT_STEP_DETAIL" MODIFY ("AUDIT_DEPARTMENT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RECRUIT_AUDIT_STEP_DETAIL" MODIFY ("AUDIT_DEPARTMENT_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "RECRUIT_AUDIT_STEP_DETAIL" MODIFY ("SORT_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "RECRUIT_AUDIT_STEP_DETAIL" MODIFY ("CURRENT_STEP_KEY" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table RECRUIT_AUDIT_STEP_SETTING
--------------------------------------------------------

  ALTER TABLE "RECRUIT_AUDIT_STEP_SETTING" MODIFY ("RECRUITMENT_CATEGORY_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "RECRUIT_AUDIT_STEP_SETTING" MODIFY ("RECRUITMENT_CATEGORY_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "RECRUIT_AUDIT_STEP_SETTING" MODIFY ("SET_AUDIT_STEP_PATH" NOT NULL ENABLE);
 
  ALTER TABLE "RECRUIT_AUDIT_STEP_SETTING" MODIFY ("CURRENT_AUDIT_STATE" NOT NULL ENABLE);
 
  ALTER TABLE "RECRUIT_AUDIT_STEP_SETTING" ADD PRIMARY KEY ("RECRUITMENT_CATEGORY_NUMBER") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table RECRUIT_BATCH_SETTING
--------------------------------------------------------

  ALTER TABLE "RECRUIT_BATCH_SETTING" ADD CONSTRAINT "BATCH_SETTING_PK" PRIMARY KEY ("BATCH_NO") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table RECRUIT_NOTICE
--------------------------------------------------------

  ALTER TABLE "RECRUIT_NOTICE" ADD PRIMARY KEY ("ID") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table RECRUIT_PLAN
--------------------------------------------------------

  ALTER TABLE "RECRUIT_PLAN" ADD PRIMARY KEY ("PLAN_ID") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table RECRUIT_RESUME_DEFINITION
--------------------------------------------------------

  ALTER TABLE "RECRUIT_RESUME_DEFINITION" ADD CONSTRAINT "PK_RESUME_DEFINITION_ID" PRIMARY KEY ("RESUME_DEFINITION_ID") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table RECRUIT_RESUME_TEMPLATE
--------------------------------------------------------

  ALTER TABLE "RECRUIT_RESUME_TEMPLATE" ADD CONSTRAINT "PK_TEMPLATE_ID" PRIMARY KEY ("RESUME_TEMPLATE_ID") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table STAFF_CAMPUS_DEPLOYMENT
--------------------------------------------------------

  ALTER TABLE "STAFF_CAMPUS_DEPLOYMENT" MODIFY ("DEPLOYMENT_KEY" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table STAFF_DEATH
--------------------------------------------------------

  ALTER TABLE "STAFF_DEATH" MODIFY ("DEATH_KEY" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table STAFF_ENGAGE_POST
--------------------------------------------------------

  ALTER TABLE "STAFF_ENGAGE_POST" ADD CONSTRAINT "ENGAGE_POST_KEY_PK" PRIMARY KEY ("ENGAGE_POST_KEY") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table STAFF_ENTRY
--------------------------------------------------------

  ALTER TABLE "STAFF_ENTRY" ADD PRIMARY KEY ("ENTRY_KEY") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table STAFF_HISTORY
--------------------------------------------------------

  ALTER TABLE "STAFF_HISTORY" ADD CONSTRAINT "HISTORY_HISTORY_KEY_PK" PRIMARY KEY ("HISTORY_KEY") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table STAFF_POSITIVE
--------------------------------------------------------

  ALTER TABLE "STAFF_POSITIVE" MODIFY ("POSITIVE_KEY" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table STAFF_POST_CHANGE
--------------------------------------------------------

  ALTER TABLE "STAFF_POST_CHANGE" ADD CONSTRAINT "POST_CHANGE_KEY_PK" PRIMARY KEY ("POST_CHANGE_KEY") ENABLE;
 
  ALTER TABLE "STAFF_POST_CHANGE" MODIFY ("POST_CHANGE_KEY" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table STAFF_REHELLORING
--------------------------------------------------------

  ALTER TABLE "STAFF_REHELLORING" ADD CONSTRAINT "REHELLORING_KEY_PK" PRIMARY KEY ("REHELLORING_KEY") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table STAFF_RESIGNATION
--------------------------------------------------------

  ALTER TABLE "STAFF_RESIGNATION" ADD PRIMARY KEY ("ID") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table STAFF_RETIREMENT
--------------------------------------------------------

  ALTER TABLE "STAFF_RETIREMENT" ADD PRIMARY KEY ("ID") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table SYS_CONFIG
--------------------------------------------------------

  ALTER TABLE "SYS_CONFIG" ADD PRIMARY KEY ("KEY") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table TASK
--------------------------------------------------------

  ALTER TABLE "TASK" MODIFY ("TASK_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "TASK" ADD CONSTRAINT "TASK_KEY_PK" PRIMARY KEY ("TASK_KEY") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table TASK_DEFINITION
--------------------------------------------------------

  ALTER TABLE "TASK_DEFINITION" MODIFY ("TASK_DEFINITION_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "TASK_DEFINITION" ADD CONSTRAINT "TASK_DEFINITION_KEY_PK" PRIMARY KEY ("TASK_DEFINITION_KEY") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table TASK_RECORD
--------------------------------------------------------

  ALTER TABLE "TASK_RECORD" MODIFY ("TASK_RECORD_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "TASK_RECORD" ADD CONSTRAINT "TASK_RECORD_KEY_PK" PRIMARY KEY ("TASK_RECORD_KEY") ENABLE;
/
--------------------------------------------------------
--  Constraints for Table VALIDATION_RULE
--------------------------------------------------------

  ALTER TABLE "VALIDATION_RULE" MODIFY ("VALIDATION_RULE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "VALIDATION_RULE" ADD CONSTRAINT "VALIDATION_RULE_PK" PRIMARY KEY ("VALIDATION_RULE_ID") ENABLE;
/
