--------------------------------------------------------
--  文件已创建 - 星期三-十月-24-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STAFF_CAMPUS_DEPLOYMENT
--------------------------------------------------------

  CREATE TABLE "LYHR"."STAFF_CAMPUS_DEPLOYMENT" 
   (	"DEPLOYMENT_KEY" VARCHAR2(40 BYTE), 
	"STAFF_ID" VARCHAR2(50 BYTE), 
	"STAFF_NAME" VARCHAR2(50 BYTE), 
	"APPROVAL_NUMBER" VARCHAR2(50 BYTE), 
	"CURRENT_DEPT" VARCHAR2(50 BYTE), 
	"CURRENT_POST" VARCHAR2(50 BYTE), 
	"DEPLOY_DATE" DATE, 
	"DEPLOY_REASON" VARCHAR2(200 BYTE), 
	"DEPLOY_POST" VARCHAR2(50 BYTE), 
	"DEPLOY_DEPT" VARCHAR2(50 BYTE), 
	"REMARK" VARCHAR2(500 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR" ;
 

   COMMENT ON COLUMN "LYHR"."STAFF_CAMPUS_DEPLOYMENT"."DEPLOYMENT_KEY" IS '主键';
 
   COMMENT ON COLUMN "LYHR"."STAFF_CAMPUS_DEPLOYMENT"."STAFF_ID" IS '员工号';
 
   COMMENT ON COLUMN "LYHR"."STAFF_CAMPUS_DEPLOYMENT"."STAFF_NAME" IS '员工姓名';
 
   COMMENT ON COLUMN "LYHR"."STAFF_CAMPUS_DEPLOYMENT"."APPROVAL_NUMBER" IS '批准文号';
 
   COMMENT ON COLUMN "LYHR"."STAFF_CAMPUS_DEPLOYMENT"."CURRENT_DEPT" IS '当前部门';
 
   COMMENT ON COLUMN "LYHR"."STAFF_CAMPUS_DEPLOYMENT"."CURRENT_POST" IS '当前岗位';
 
   COMMENT ON COLUMN "LYHR"."STAFF_CAMPUS_DEPLOYMENT"."DEPLOY_DATE" IS '调岗日期';
 
   COMMENT ON COLUMN "LYHR"."STAFF_CAMPUS_DEPLOYMENT"."DEPLOY_REASON" IS '调配原因';
 
   COMMENT ON COLUMN "LYHR"."STAFF_CAMPUS_DEPLOYMENT"."DEPLOY_POST" IS '调配岗位';
 
   COMMENT ON COLUMN "LYHR"."STAFF_CAMPUS_DEPLOYMENT"."DEPLOY_DEPT" IS '调配部门';
 
   COMMENT ON COLUMN "LYHR"."STAFF_CAMPUS_DEPLOYMENT"."REMARK" IS '备注';
--------------------------------------------------------
--  DDL for Table STAFF_DEATH
--------------------------------------------------------

  CREATE TABLE "LYHR"."STAFF_DEATH" 
   (	"DEATH_KEY" VARCHAR2(40 BYTE), 
	"STAFF_ID" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"DEATH_DATE" DATE, 
	"DEATH_REASON" VARCHAR2(200 BYTE), 
	"DEATH_REMARK" VARCHAR2(500 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR" ;
--------------------------------------------------------
--  DDL for Table STAFF_DEFINITION
--------------------------------------------------------

  CREATE TABLE "LYHR"."STAFF_DEFINITION" 
   (	"STAFF_DEFINITION_KEY" VARCHAR2(40 BYTE), 
	"STAFF_DEFINITION_COLUMNS" CLOB, 
	"STAFF_DEFINITION_TABLE_NAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR" 
 LOB ("STAFF_DEFINITION_COLUMNS") STORE AS (
  TABLESPACE "LYHR" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table STAFF_ENTRY
--------------------------------------------------------

  CREATE TABLE "LYHR"."STAFF_ENTRY" 
   (	
   "ENTRY_KEY" VARCHAR2(40 BYTE), 
	"STAFF_ID" VARCHAR2(50 BYTE), 
	"ENTRY_DATE" DATE, 
	"STAFF_SOURCE" VARCHAR2(50 BYTE), 
	"APPROVALNUM" VARCHAR2(50 BYTE), 
	"END_DATE" DATE, 
	"ENTRY_STATUS" VARCHAR2(50 BYTE), 
	"STAFF_DELETE_STATUS" NUMBER, 
	"STAFF_NAME" VARCHAR2(60 BYTE), 
	"REMARK" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR" ;
 

   COMMENT ON COLUMN "LYHR"."STAFF_ENTRY"."ENTRY_KEY" IS '入职表Key';
 
   COMMENT ON COLUMN "LYHR"."STAFF_ENTRY"."STAFF_ID" IS '职工号';
 
   COMMENT ON COLUMN "LYHR"."STAFF_ENTRY"."ENTRY_DATE" IS '入职日期';
 
   COMMENT ON COLUMN "LYHR"."STAFF_ENTRY"."STAFF_SOURCE" IS '教职工来源';
 
   COMMENT ON COLUMN "LYHR"."STAFF_ENTRY"."APPROVALNUM" IS '批准文号';
 
   COMMENT ON COLUMN "LYHR"."STAFF_ENTRY"."END_DATE" IS '试用到期日期';
 
   COMMENT ON COLUMN "LYHR"."STAFF_ENTRY"."ENTRY_STATUS" IS '18.在岗, 19试用';
 
   COMMENT ON COLUMN "LYHR"."STAFF_ENTRY"."STAFF_DELETE_STATUS" IS '0:删除,1:彻底删除';
 
   COMMENT ON COLUMN "LYHR"."STAFF_ENTRY"."STAFF_NAME" IS '职工姓名';
 
   COMMENT ON COLUMN "LYHR"."STAFF_ENTRY"."REMARK" IS '描述';
--------------------------------------------------------
--  DDL for Table STAFF_HISTORY
--------------------------------------------------------

  CREATE TABLE "LYHR"."STAFF_HISTORY" 
   (	"HISTORY_KEY" VARCHAR2(40 BYTE), 
	"CHANGE_TYPE" VARCHAR2(40 BYTE), 
	"CHANGE_REASON" VARCHAR2(50 BYTE), 
	"CHANGE_DESC" VARCHAR2(100 BYTE), 
	"CHANGE_RESULT" VARCHAR2(100 BYTE), 
	"CHANGE_DATE" DATE, 
	"STAFF_ID" VARCHAR2(50 BYTE), 
	"STAFF_NAME" VARCHAR2(60 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR" ;
 

   COMMENT ON COLUMN "LYHR"."STAFF_HISTORY"."HISTORY_KEY" IS '历史Key';
 
   COMMENT ON COLUMN "LYHR"."STAFF_HISTORY"."CHANGE_TYPE" IS '变动类型';
 
   COMMENT ON COLUMN "LYHR"."STAFF_HISTORY"."CHANGE_REASON" IS '变动原因';
 
   COMMENT ON COLUMN "LYHR"."STAFF_HISTORY"."CHANGE_DESC" IS '变动说明';
 
   COMMENT ON COLUMN "LYHR"."STAFF_HISTORY"."CHANGE_RESULT" IS '变动结果';
 
   COMMENT ON COLUMN "LYHR"."STAFF_HISTORY"."CHANGE_DATE" IS '变动日期';
 
   COMMENT ON COLUMN "LYHR"."STAFF_HISTORY"."STAFF_ID" IS '职工号';
 
   COMMENT ON COLUMN "LYHR"."STAFF_HISTORY"."STAFF_NAME" IS '职工姓名';
--------------------------------------------------------
--  DDL for Table STAFF_POSITIVE
--------------------------------------------------------

  CREATE TABLE "LYHR"."STAFF_POSITIVE" 
   (	"POSITIVE_KEY" VARCHAR2(40 BYTE), 
	"STAFF_ID" VARCHAR2(40 BYTE), 
	"STAFF_NAME" VARCHAR2(50 BYTE), 
	"DEFER_POSITIVE" DATE, 
	"POSITIVE_REASON" VARCHAR2(200 BYTE), 
	"APPROVAL_NUMBER" VARCHAR2(50 BYTE), 
	"DEPARTMENT" VARCHAR2(50 BYTE), 
	"POSITION" VARCHAR2(50 BYTE), 
	"REMARK" VARCHAR2(500 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR" ;
--------------------------------------------------------
--  DDL for Table STAFF_POST_CHANGE
--------------------------------------------------------

-- DROP table
DROP TABLE STAFF_POST_CHANGE

-- CREATE TABLE
CREATE TABLE STAFF_POST_CHANGE
(
  POST_CHANGE_KEY        VARCHAR2(50) NOT NULL,
  STAFF_ID               VARCHAR2(50),
  STAFF_NAME             VARCHAR2(100),
  POST_NAME              VARCHAR2(100),
  POST_CATEGORY          VARCHAR2(50),
  POST_LEVEL             VARCHAR2(50),
  APPOINTMENT_DATE       DATE,
  APPOINTMENT_DEPT_KEY   VARCHAR2(50),
  APPOINTMENT_DEPT_NAME  VARCHAR2(100),
  APPROVE_DEPT_KEY       VARCHAR2(50),
  APPROVE_DEPT_NAME      VARCHAR2(100),
  APPROVAL_NUMBER        VARCHAR2(50),
  APPOINTMENT_MODE       VARCHAR2(300),
  WORK_CONTENT           VARCHAR2(200),
  APPOINTMENT_STATUS     VARCHAR2(10),
  MIDDLE_CADRES          CHAR(1),
  PART_TIME              CHAR(1),
  REMARK                 VARCHAR2(300),
  DISMISSAL_DATE         DATE,
  DISMISSAL_REASON       VARCHAR2(300),
  CURRENT_STATUS         CHAR(1),
  CREATE_TIME            DATE,
  POST_CATEGORY_KEY      VARCHAR2(50),
  POST_LEVEL_KEY         VARCHAR2(50),
  APPOINTMENT_MODE_KEY   VARCHAR2(50),
  DISMISSAL_REASON_KEY   VARCHAR2(50),
  APPOINTMENT_END_DATE   DATE,
  APPOINTMENT_REASON     VARCHAR2(50),
  APPOINTMENT_REASON_KEY VARCHAR2(50)
)
TABLESPACE LYHR
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 16
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN STAFF_POST_CHANGE.POST_CHANGE_KEY
  IS '主键';
COMMENT ON COLUMN STAFF_POST_CHANGE.STAFF_ID
  IS '人员编号';
COMMENT ON COLUMN STAFF_POST_CHANGE.STAFF_NAME
  IS '姓名';
COMMENT ON COLUMN STAFF_POST_CHANGE.POST_NAME
  IS '职务名称';
COMMENT ON COLUMN STAFF_POST_CHANGE.POST_CATEGORY
  IS '职务类别名称';
COMMENT ON COLUMN STAFF_POST_CHANGE.POST_LEVEL
  IS '职务级别名称';
COMMENT ON COLUMN STAFF_POST_CHANGE.APPOINTMENT_DATE
  IS '任职开始日期';
COMMENT ON COLUMN STAFF_POST_CHANGE.APPOINTMENT_DEPT_KEY
  IS '任职部门编号';
COMMENT ON COLUMN STAFF_POST_CHANGE.APPOINTMENT_DEPT_NAME
  IS '任职部门名称';
COMMENT ON COLUMN STAFF_POST_CHANGE.APPROVE_DEPT_KEY
  IS '任职批准单位编号';
COMMENT ON COLUMN STAFF_POST_CHANGE.APPROVE_DEPT_NAME
  IS '任职批准单位名称';
COMMENT ON COLUMN STAFF_POST_CHANGE.APPROVAL_NUMBER
  IS '批准文号';
COMMENT ON COLUMN STAFF_POST_CHANGE.APPOINTMENT_MODE
  IS '任职方式名称';
COMMENT ON COLUMN STAFF_POST_CHANGE.WORK_CONTENT
  IS '主管或从事的工作';
COMMENT ON COLUMN STAFF_POST_CHANGE.APPOINTMENT_STATUS
  IS '当前任职状况';
COMMENT ON COLUMN STAFF_POST_CHANGE.MIDDLE_CADRES
  IS '是否中层干部(取值1或空)';
COMMENT ON COLUMN STAFF_POST_CHANGE.PART_TIME
  IS '是否兼职(取值1或空)';
COMMENT ON COLUMN STAFF_POST_CHANGE.REMARK
  IS '备注';
COMMENT ON COLUMN STAFF_POST_CHANGE.DISMISSAL_DATE
  IS '免职日期';
COMMENT ON COLUMN STAFF_POST_CHANGE.DISMISSAL_REASON
  IS '免职原因';
COMMENT ON COLUMN STAFF_POST_CHANGE.CURRENT_STATUS
  IS '当前状态';
COMMENT ON COLUMN STAFF_POST_CHANGE.CREATE_TIME
  IS '创建日期';
COMMENT ON COLUMN STAFF_POST_CHANGE.POST_CATEGORY_KEY
  IS '职务类别编号';
COMMENT ON COLUMN STAFF_POST_CHANGE.POST_LEVEL_KEY
  IS '职务级别编号';
COMMENT ON COLUMN STAFF_POST_CHANGE.APPOINTMENT_MODE_KEY
  IS '任职方式编号';
COMMENT ON COLUMN STAFF_POST_CHANGE.DISMISSAL_REASON_KEY
  IS '免职原因编号';
COMMENT ON COLUMN STAFF_POST_CHANGE.APPOINTMENT_END_DATE
  IS '任职结束日期';
COMMENT ON COLUMN STAFF_POST_CHANGE.APPOINTMENT_REASON
  IS '任职原因';
COMMENT ON COLUMN STAFF_POST_CHANGE.APPOINTMENT_REASON_KEY
  IS '任职原因编号';
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE STAFF_POST_CHANGE
  ADD CONSTRAINT POST_CHANGE_KEY_PK PRIMARY KEY (POST_CHANGE_KEY)
  USING INDEX 
  TABLESPACE LYHR
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );


--------------------------------------------------------
--  DDL for Table STAFF_REHELLORING
--------------------------------------------------------

  CREATE TABLE "LYHR"."STAFF_REHELLORING" 
   (	"REHELLORING_KEY" VARCHAR2(40 BYTE), 
	"STAFF_ID" VARCHAR2(50 BYTE), 
	"STAFF_NAME" VARCHAR2(60 BYTE), 
	"REHELLORING_DEPT" VARCHAR2(50 BYTE), 
	"APPROVAL_NUM" VARCHAR2(50 BYTE), 
	"CHANGE_REASON" VARCHAR2(100 BYTE), 
	"POST_TYPE" VARCHAR2(30 BYTE), 
	"POST_LEVEL" VARCHAR2(30 BYTE), 
	"AGREEMENT" NUMBER(1,0), 
	"WORK_THIRTY_AGE" NUMBER(1,0), 
	"SPECIAL_PERSON" NUMBER(1,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"REMARK" VARCHAR2(200 BYTE), 
	"REHELLORING_STATUS" VARCHAR2(50 BYTE), 
	"STOP_DATE" DATE, 
	"STOP_REASON" VARCHAR2(100 BYTE), 
	"STOP_DEPT" VARCHAR2(50 BYTE), 
	"STOP_APPROVAL_NUM" VARCHAR2(50 BYTE), 
	"STOP_REMARK" VARCHAR2(200 BYTE), 
	"REHELLORING_DEPT_KEY" VARCHAR2(50 BYTE), 
	"REHELLORING_POST" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR" ;
 

   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."REHELLORING_KEY" IS '主键';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."STAFF_ID" IS '职工号';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."STAFF_NAME" IS '职工姓名';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."REHELLORING_DEPT" IS '返聘部门';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."APPROVAL_NUM" IS '返聘批准文号';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."CHANGE_REASON" IS '变动原因';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."POST_TYPE" IS '返聘岗位类型';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."POST_LEVEL" IS '返聘岗位级别';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."AGREEMENT" IS '是否签订返聘协议';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."WORK_THIRTY_AGE" IS '是否30年工龄';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."SPECIAL_PERSON" IS '是否特殊人物';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."START_DATE" IS '返聘开始日期';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."END_DATE" IS '返聘结束日期';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."REMARK" IS '备注';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."REHELLORING_STATUS" IS '返聘人员状态(返聘/退休)';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."STOP_DATE" IS '终止返聘日期';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."STOP_REASON" IS '终止返聘原因';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."STOP_DEPT" IS '终止返聘后部门';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."STOP_APPROVAL_NUM" IS '终止返聘批准文号';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."STOP_REMARK" IS '终止返聘描述';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."REHELLORING_DEPT_KEY" IS '返聘部门Key';
 
   COMMENT ON COLUMN "LYHR"."STAFF_REHELLORING"."REHELLORING_POST" IS '返聘岗位';
--------------------------------------------------------
--  DDL for Table STAFF_RESIGNATION
--------------------------------------------------------

  CREATE TABLE "LYHR"."STAFF_RESIGNATION" 
   (	"ID" VARCHAR2(40 BYTE), 
	"STAFF_ID" VARCHAR2(40 BYTE), 
	"RESIGNATION_DATE" DATE, 
	"APPOINT_FILE_NUMBER" VARCHAR2(100 BYTE), 
	"RESIGNATION_REASON" VARCHAR2(500 BYTE), 
	"REMARK" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR" 
 LOB ("REMARK") STORE AS (
  TABLESPACE "LYHR" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
 

   COMMENT ON COLUMN "LYHR"."STAFF_RESIGNATION"."ID" IS '主键';
 
   COMMENT ON COLUMN "LYHR"."STAFF_RESIGNATION"."STAFF_ID" IS '员工编号';
 
   COMMENT ON COLUMN "LYHR"."STAFF_RESIGNATION"."RESIGNATION_DATE" IS '离职日期';
 
   COMMENT ON COLUMN "LYHR"."STAFF_RESIGNATION"."APPOINT_FILE_NUMBER" IS '批准文号';
 
   COMMENT ON COLUMN "LYHR"."STAFF_RESIGNATION"."RESIGNATION_REASON" IS '辞（离）职原因';
 
   COMMENT ON COLUMN "LYHR"."STAFF_RESIGNATION"."REMARK" IS '描述';
--------------------------------------------------------
--  DDL for Table STAFF_RETIREMENT
--------------------------------------------------------

  CREATE TABLE "LYHR"."STAFF_RETIREMENT" 
   (	"ID" VARCHAR2(40 BYTE), 
	"STAFF_ID" VARCHAR2(40 BYTE), 
	"RETIRE_REASON" VARCHAR2(40 BYTE), 
	"RETIRE_DATE" DATE, 
	"RETIREE_PREMIUMS_PROPORTION" NUMBER(4,2), 
	"RETURN_OVERSEAS" NUMBER(4,2), 
	"PROPORTION_TOTAL" NUMBER(4,2), 
	"REMARK" CLOB, 
	"THREETY_STAFF_SERVICE" NUMBER(1,0), 
	"SPECIAL_STAFF" NUMBER(1,0), 
	"ONLY_CHILD" NUMBER(1,0), 
	"OVERSEAS_CHINESE" NUMBER(1,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR" 
 LOB ("REMARK") STORE AS (
  TABLESPACE "LYHR" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
 

   COMMENT ON COLUMN "LYHR"."STAFF_RETIREMENT"."ID" IS '主键';
 
   COMMENT ON COLUMN "LYHR"."STAFF_RETIREMENT"."STAFF_ID" IS '员工编号';
 
   COMMENT ON COLUMN "LYHR"."STAFF_RETIREMENT"."RETIRE_REASON" IS '退休原因';
 
   COMMENT ON COLUMN "LYHR"."STAFF_RETIREMENT"."RETIRE_DATE" IS '退休日期';
 
   COMMENT ON COLUMN "LYHR"."STAFF_RETIREMENT"."RETIREE_PREMIUMS_PROPORTION" IS '退休费计发比例';
 
   COMMENT ON COLUMN "LYHR"."STAFF_RETIREMENT"."RETURN_OVERSEAS" IS '归侨比例';
 
   COMMENT ON COLUMN "LYHR"."STAFF_RETIREMENT"."PROPORTION_TOTAL" IS '比例总计';
 
   COMMENT ON COLUMN "LYHR"."STAFF_RETIREMENT"."REMARK" IS '备注';
 
   COMMENT ON COLUMN "LYHR"."STAFF_RETIREMENT"."THREETY_STAFF_SERVICE" IS '是否30年工龄';
 
   COMMENT ON COLUMN "LYHR"."STAFF_RETIREMENT"."SPECIAL_STAFF" IS '是否特殊人员';
 
   COMMENT ON COLUMN "LYHR"."STAFF_RETIREMENT"."ONLY_CHILD" IS '是否独生子女';
 
   COMMENT ON COLUMN "LYHR"."STAFF_RETIREMENT"."OVERSEAS_CHINESE" IS '是否华侨';
   
   
--------------------------------------------------------
---DDL for Table STAFF_ENGAGE_POST20121112
--------------------------------------------------------   
 CREATE TABLE  "STAFF_ENGAGE_POST"
(
  ENGAGE_POST_KEY     VARCHAR2(40 BYTE),
  STAFF_ID            VARCHAR2(50 BYTE),
  STAFF_NAME          VARCHAR2(60 BYTE),
  ENGAGE_POST_TYPE    VARCHAR2(50 BYTE),
  ENGAGE_POST_STATUS  NUMBER,
  ENGAGE_DEPART       VARCHAR2(100 BYTE),
  ENGAGE_DEPART_KEY   VARCHAR2(40 BYTE),
  ENGAGE_POST_LEVEL   VARCHAR2(50 BYTE),
  START_DATE          DATE,
  END_DATE            DATE
)
TABLESPACE "LYHR"
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN STAFF_ENGAGE_POST.ENGAGE_POST_KEY IS '主键';

COMMENT ON COLUMN STAFF_ENGAGE_POST.STAFF_ID IS '职工号';

COMMENT ON COLUMN STAFF_ENGAGE_POST.STAFF_NAME IS '职工姓名';

COMMENT ON COLUMN STAFF_ENGAGE_POST.ENGAGE_POST_TYPE IS '岗位类别';

COMMENT ON COLUMN STAFF_ENGAGE_POST.ENGAGE_POST_STATUS IS '聘岗状态0未聘1已聘2历史';

COMMENT ON COLUMN STAFF_ENGAGE_POST.ENGAGE_DEPART IS '聘任部门';

COMMENT ON COLUMN STAFF_ENGAGE_POST.ENGAGE_DEPART_KEY IS '聘任部门Key';

COMMENT ON COLUMN STAFF_ENGAGE_POST.ENGAGE_POST_LEVEL IS '岗位级别';

COMMENT ON COLUMN STAFF_ENGAGE_POST.START_DATE IS '开始日期';

COMMENT ON COLUMN STAFF_ENGAGE_POST.END_DATE IS '终止日期';  
   
 
--------------------------------------------------------
--  DDL for Index SYS_C005438
--------------------------------------------------------

  CREATE UNIQUE INDEX "LYHR"."SYS_C005438" ON "LYHR"."STAFF_ENTRY" ("ENTRY_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR" ;

--------------------------------------------------------
--  DDL for Index HISTORY_HISTORY_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LYHR"."HISTORY_HISTORY_KEY_PK" ON "LYHR"."STAFF_HISTORY" ("HISTORY_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR" ;  
  
--------------------------------------------------------
--  DDL for Index POST_CHANGE_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LYHR"."POST_CHANGE_KEY_PK" ON "LYHR"."STAFF_POST_CHANGE" ("POST_CHANGE_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR" ;  
  
--------------------------------------------------------
--  DDL for Index REHELLORING_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LYHR"."REHELLORING_KEY_PK" ON "LYHR"."STAFF_REHELLORING" ("REHELLORING_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR" ;
  
--------------------------------------------------------
--  DDL for Index SYS_C005427
--------------------------------------------------------

  CREATE UNIQUE INDEX "LYHR"."SYS_C005427" ON "LYHR"."STAFF_RESIGNATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR" ;  
  

--------------------------------------------------------
--  DDL for Index SYS_C005475
--------------------------------------------------------

  CREATE UNIQUE INDEX "LYHR"."SYS_C005475" ON "LYHR"."STAFF_RETIREMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR" ;  
  


--------------------------------------------------------
--  Constraints for Table STAFF_CAMPUS_DEPLOYMENT
--------------------------------------------------------

  ALTER TABLE "LYHR"."STAFF_CAMPUS_DEPLOYMENT" MODIFY ("DEPLOYMENT_KEY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STAFF_DEATH
--------------------------------------------------------

  ALTER TABLE "LYHR"."STAFF_DEATH" MODIFY ("DEATH_KEY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STAFF_ENTRY
--------------------------------------------------------

  ALTER TABLE "LYHR"."STAFF_ENTRY" ADD PRIMARY KEY ("ENTRY_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR"  ENABLE;
  
--------------------------------------------------------
--  Constraints for Table STAFF_HISTORY
--------------------------------------------------------

  ALTER TABLE "LYHR"."STAFF_HISTORY" ADD CONSTRAINT "HISTORY_HISTORY_KEY_PK" PRIMARY KEY ("HISTORY_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STAFF_POSITIVE
--------------------------------------------------------

  ALTER TABLE "LYHR"."STAFF_POSITIVE" MODIFY ("POSITIVE_KEY" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table STAFF_REHELLORING
--------------------------------------------------------

  ALTER TABLE "LYHR"."STAFF_REHELLORING" ADD CONSTRAINT "REHELLORING_KEY_PK" PRIMARY KEY ("REHELLORING_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STAFF_RESIGNATION
--------------------------------------------------------

  ALTER TABLE "LYHR"."STAFF_RESIGNATION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STAFF_RETIREMENT
--------------------------------------------------------

  ALTER TABLE "LYHR"."STAFF_RETIREMENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYHR"  ENABLE;
  
alter table ds_overall add x__personnel_status varchar(80);
alter table ds_overall add x__emp_identifition varchar(80);
alter table ds_overall add x__parttime_department_key varchar(80);

alter table STAFF_POSITIVE add REALLY_POSITIVE_DATE date;
alter table STAFF_POSITIVE add REALLY_POSITIVE_DATE date;


  
------------------------------------------------------
---DDL for Index  ENGAGE_POST_KEY_PK(20121109)
------------------------------------------------------

CREATE UNIQUE INDEX "ENGAGE_POST_KEY_PK" ON "STAFF_ENGAGE_POST"
("ENGAGE_POST_KEY")
LOGGING
TABLESPACE "LYHR"
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;
  
 --------------------------------------------------------
--  Constraints for Table STAFF_ENGAGE_POST(20121109)
-------------------------------------------------------- 
 ALTER TABLE "STAFF_ENGAGE_POST" ADD (
  CONSTRAINT "ENGAGE_POST_KEY_PK"
 PRIMARY KEY
 ("ENGAGE_POST_KEY")
    USING INDEX 
    TABLESPACE "LYHR"
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               )); 
  

--------------------------------------------------
---20121109
----------------------------------------------------
alter table staff_engage_post add really_stop_date date;
alter table STAFF_POSITIVE add REALLY_POSITIVE_DATE date;
alter table STAFF_HISTORY add CREATE_TIME date;



alter table STAFF_ENTRY add EXTEND_TIME number;
alter table STAFF_ENTRY add EXTEND_REASON varchar(50);
alter table STAFF_ENTRY add PROBATION_TIME number;


alter table STAFF_CAMPUS_DEPLOYMENT add DEPLOY_DEPT_KEY varchar(50);


-------------------------------------
---DDL for Table STAFF_RETIREMENT20121109
-------------------------------------
create table PERSONAL_DEFINITION
(
  personal_definition_key        VARCHAR2(40) not null,
  personal_definition_columns    CLOB,
  personal_definition_table_name  VARCHAR2(50)
)
tablespace "LYHR"
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    minextents 1
    maxextents unlimited
  );
----------------------------------------------
---Constraints for Table PERSONAL_DEFINITION
----------------------------------------------
alter table "LYHR"."PERSONAL_DEFINITION"
  add constraint "PERSONAL_DEFINITION_KEY_PK" primary key ("PERSONAL_DEFINITION_KEY")
  using index 
  tablespace "LYHR"
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    minextents 1
    maxextents unlimited
  );

insert into sys_config (key,value) 
values('retirement_age','female employees:60,female cadres:60,male employees:60,male cadres:60,reminders:5'); 



alter table STAFF_CAMPUS_DEPLOYMENT add DEPLOY_POST_KEY varchar(40);
alter table STAFF_POSITIVE add POSITION_KEY varchar(40);


 

-------------------------------------
---Constraints for Table STAFF_HISTORY 20121114
-------------------------------------
alter table STAFF_HISTORY add HISTORY_DETAIL_KEY varchar(50);
-------------------------------------
---Constraints for Table STAFF_HISTORY 20121115
-------------------------------------
alter table STAFF_POSITIVE add DEPARTMENT_KEY varchar(40);

alter table STAFF_HISTORY add FORMER_STATUS varchar(10);
-------------------------------------
---Constraints for Table STAFF_REHELLORING 20121122
-------------------------------------
alter table STAFF_REHELLORING add REHELLORING_POST_KEY varchar(50);
alter table STAFF_REHELLORING add STOP_DEPT_KEY varchar(50);
delete from CODE_CATALOG t where t.catalog_id='DM_STUDY_QUALITY';
