-----------------------同步的用户中间表创建S-------------------------
  CREATE TABLE "LYHR_BMP_SYNC" 
   (	"ID" VARCHAR2(50 BYTE), 
	"TEACHER_KEY" VARCHAR2(50 BYTE), 
	"TEACHER_NAME" VARCHAR2(50 BYTE), 
	"MOBILE_PHONE" VARCHAR2(50 BYTE), 
	"DEPT_KEY" VARCHAR2(50 BYTE), 
	"OPERATE" VARCHAR2(50 BYTE), 
	"STATE" VARCHAR2(50 BYTE), 
	"OPERATEDATA" NUMBER, 
	"WORK_PHONE" VARCHAR2(50 BYTE), 
	"INSERTTIME" TIMESTAMP (6), 
	"SORT_NUM" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 917504 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYOA" ;
 

   COMMENT ON COLUMN "LYHR_BMP_SYNC"."TEACHER_KEY" IS '教师id';
 
   COMMENT ON COLUMN "LYHR_BMP_SYNC"."TEACHER_NAME" IS '教师名称';
 
   COMMENT ON COLUMN "LYHR_BMP_SYNC"."MOBILE_PHONE" IS '手机号码';
 
   COMMENT ON COLUMN "LYHR_BMP_SYNC"."DEPT_KEY" IS '部门';
 
   COMMENT ON COLUMN "LYHR_BMP_SYNC"."OPERATE" IS '操作：1.新增，2.修改，3.删除';
 
   COMMENT ON COLUMN "LYHR_BMP_SYNC"."STATE" IS '状态：0.待同步，1.已同步';
 
   COMMENT ON COLUMN "LYHR_BMP_SYNC"."OPERATEDATA" IS '操作时间';
 
   COMMENT ON COLUMN "LYHR_BMP_SYNC"."INSERTTIME" IS '数据插入此同步表的日期';
 
   COMMENT ON COLUMN "LYHR_BMP_SYNC"."SORT_NUM" IS '人员排序号';
 
   COMMENT ON TABLE "LYHR_BMP_SYNC"  IS 'oa同步工作流中间表';
   
   -----------------------------同步的用户中间表创建E---------------------------------
   
   -----------------------------同步的部门中间表创建S---------------------------------
  CREATE TABLE "LYHR_BMP_SYNC_DEP" 
   (	"ID" VARCHAR2(50 BYTE), 
	"DEPT_KEY" VARCHAR2(50 BYTE), 
	"DEPT_NAME" VARCHAR2(255 BYTE), 
	"PARENT_KEY" VARCHAR2(50 BYTE), 
	"SORT_NUM" VARCHAR2(50 BYTE), 
	"STATE" VARCHAR2(50 BYTE), 
	"OPERATEDATA" NUMBER, 
	"OPERATE" VARCHAR2(50 BYTE), 
	"INSERTTIME" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LYOA" ;
 

   COMMENT ON COLUMN "LYHR_BMP_SYNC_DEP"."DEPT_KEY" IS '部门id';
 
   COMMENT ON COLUMN "LYHR_BMP_SYNC_DEP"."DEPT_NAME" IS '部门名称';
 
   COMMENT ON COLUMN "LYHR_BMP_SYNC_DEP"."PARENT_KEY" IS '上级菜单';
 
   COMMENT ON COLUMN "LYHR_BMP_SYNC_DEP"."SORT_NUM" IS '排序号';
 
   COMMENT ON COLUMN "LYHR_BMP_SYNC_DEP"."STATE" IS '状态：0.待同步，1.已同步';
 
   COMMENT ON COLUMN "LYHR_BMP_SYNC_DEP"."OPERATEDATA" IS '操作时间';
 
   COMMENT ON COLUMN "LYHR_BMP_SYNC_DEP"."OPERATE" IS '操作：1.新增，2.修改，3.删除';
 
   COMMENT ON COLUMN "LYHR_BMP_SYNC_DEP"."INSERTTIME" IS '数据插入时间';
 
   COMMENT ON TABLE "LYHR_BMP_SYNC_DEP"  IS 'oa同步工作流部门中间表';
 -----------------------------同步的部门中间表创建E---------------------------------
   
 
